### ISSUE TITLE
A thread (Download metadata thread/63) died unexpectedly due to an uncaught exception

### ISSUE THREAD

**Issue by kastl-ars** [jenkinsci/helm-charts#1125]
### Describe the bug

I installed Jenkins using the values file given below, but it fails to start:

```
jenkins-0 jenkins Running from: /usr/share/jenkins/jenkins.war                                                                                                                                                                                               
jenkins-0 jenkins 2024-06-10 13:30:58.335+0000 [id=1]   INFO    winstone.Logger#logInternal: Beginning extraction from war file
jenkins-0 jenkins 2024-06-10 13:31:07.055+0000 [id=1]   WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
jenkins-0 jenkins 2024-06-10 13:31:08.138+0000 [id=1]   INFO    org.eclipse.jetty.server.Server#doStart: jetty-10.0.20; built: 2024-01-29T20:46:45.278Z; git: 3a745c71c23682146f262b99f4ddc4c1bc41630c; jvm 17.0.11+9
jenkins-0 jenkins 2024-06-10 13:31:11.948+0000 [id=1]   INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
jenkins-0 jenkins 2024-06-10 13:31:12.541+0000 [id=1]   INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: Session workerName=node0
jenkins-0 jenkins 2024-06-10 13:31:21.143+0000 [id=1]   INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins-0 jenkins 2024-06-10 13:31:23.136+0000 [id=1]   INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@4d8286c4{Jenkins v2.452.1,/,file:///var/jenkins_cache/war/,AVAILABLE}{/var/jenkins_cache/war}
jenkins-0 jenkins 2024-06-10 13:31:23.442+0000 [id=1]   INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@3a1dd365{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
jenkins-0 jenkins 2024-06-10 13:31:23.747+0000 [id=1]   INFO    org.eclipse.jetty.server.Server#doStart: Started Server@f001896{STARTING}[10.0.20,sto=0] @33001ms
jenkins-0 jenkins 2024-06-10 13:31:23.847+0000 [id=26]  INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
jenkins-0 jenkins 2024-06-10 13:31:28.339+0000 [id=32]  INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization                                                                                                                               
jenkins-0 jenkins 2024-06-10 13:31:33.742+0000 [id=31]  INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins    
jenkins-0 jenkins 2024-06-10 13:32:25.536+0000 [id=31]  INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins                                                                                                                                 
jenkins-0 jenkins 2024-06-10 13:32:26.839+0000 [id=32]  INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
jenkins-0 jenkins 2024-06-10 13:32:36.340+0000 [id=27]  INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty                                                                                                                         
jenkins-0 jenkins 2024-06-10 13:32:36.341+0000 [id=27]  INFO    org.eclipse.jetty.server.Server#doStop: Stopped Server@f001896{STOPPING}[10.0.20,sto=0]                                                                                                      
jenkins-0 jenkins 2024-06-10 13:32:36.435+0000 [id=27]  INFO    o.e.j.server.AbstractConnector#doStop: Stopped ServerConnector@3a1dd365{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}                                                                                  
jenkins-0 jenkins 2024-06-10 13:32:36.537+0000 [id=27]  INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins                                                                                                                                  
jenkins-0 jenkins 2024-06-10 13:32:43.643+0000 [id=31]  INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions                                                                                                                             
jenkins-0 jenkins 2024-06-10 13:32:51.345+0000 [id=27]  INFO    jenkins.model.Jenkins$16#onAttained: Started termination                                                                                                                                     
jenkins-0 jenkins 2024-06-10 13:32:51.840+0000 [id=27]  INFO    jenkins.model.Jenkins$16#onAttained: Completed termination                                                                                                                                   
jenkins-0 jenkins 2024-06-10 13:32:51.841+0000 [id=27]  INFO    jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection                                                                                                               
jenkins-0 jenkins 2024-06-10 13:32:51.849+0000 [id=32]  INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded                                                                                                                                 
jenkins-0 jenkins 2024-06-10 13:32:52.046+0000 [id=27]  INFO    jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager                                                                                                                 
jenkins-0 jenkins 2024-06-10 13:32:52.342+0000 [id=32]  WARNING jenkins.model.Jenkins$5#runTask: ConfigurationAsCode.init failed perhaps due to plugin dependency issues                                                                                     
jenkins-0 jenkins java.lang.ClassNotFoundException: io.jenkins.plugins.casc.VersionConverter                                  
jenkins-0 jenkins       at java.base/java.net.URLClassLoader.findClass(Unknown Source)                                        
jenkins-0 jenkins       at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:35)                                    
jenkins-0 jenkins       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jenkins-0 jenkins Caused: java.lang.NoClassDefFoundError: io/jenkins/plugins/casc/VersionConverter
jenkins-0 jenkins       at io.jenkins.plugins.casc.ConfigurationContext.<clinit>(ConfigurationContext.java:193)
jenkins-0 jenkins       at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:694)
jenkins-0 jenkins       at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:352)
jenkins-0 jenkins       at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:341)
jenkins-0 jenkins Caused: java.lang.reflect.InvocationTargetException
jenkins-0 jenkins       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins-0 jenkins       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jenkins-0 jenkins       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jenkins-0 jenkins       at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
jenkins-0 jenkins Caused: java.lang.Error
jenkins-0 jenkins       at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:115)
jenkins-0 jenkins       at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
jenkins-0 jenkins       at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
jenkins-0 jenkins       at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
jenkins-0 jenkins       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jenkins-0 jenkins       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.Thread.run(Unknown Source)
jenkins-0 jenkins 2024-06-10 13:32:52.343+0000 [id=32]  INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
jenkins-0 jenkins 2024-06-10 13:32:52.344+0000 [id=32]  INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
jenkins-0 jenkins 2024-06-10 13:32:52.347+0000 [id=27]  INFO    jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
jenkins-0 jenkins 2024-06-10 13:32:52.544+0000 [id=32]  WARNING h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=com.cloudbees.plugins.credentials.SystemCredentialsProvider, annotation=[none]]; skipping this compo
nent
jenkins-0 jenkins java.lang.ClassNotFoundException: com.cloudbees.plugins.credentials.CredentialsStore$1
jenkins-0 jenkins       at java.base/java.net.URLClassLoader.findClass(Unknown Source)
jenkins-0 jenkins       at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:35)
jenkins-0 jenkins       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jenkins-0 jenkins Caused: java.lang.NoClassDefFoundError: com/cloudbees/plugins/credentials/CredentialsStore$1
jenkins-0 jenkins       at com.cloudbees.plugins.credentials.SystemCredentialsProvider.<init>(SystemCredentialsProvider.java:103)
jenkins-0 jenkins       at com.cloudbees.plugins.credentials.SystemCredentialsProvider$$FastClassByGuice$$1cb72f3b.GUICE$TRAMPOLINE(<generated>)
jenkins-0 jenkins       at com.cloudbees.plugins.credentials.SystemCredentialsProvider$$FastClassByGuice$$1cb72f3b.apply(<generated>)
jenkins-0 jenkins       at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
jenkins-0 jenkins       at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
jenkins-0 jenkins       at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
jenkins-0 jenkins       at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
jenkins-0 jenkins       at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
jenkins-0 jenkins       at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:613)
jenkins-0 jenkins       at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
jenkins-0 jenkins       at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
jenkins-0 jenkins       at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
jenkins-0 jenkins       at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
jenkins-0 jenkins       at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
jenkins-0 jenkins Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:
jenkins-0 jenkins 
jenkins-0 jenkins 1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: com/cloudbees/plugins/credentials/CredentialsStore$1
jenkins-0 jenkins   at SystemCredentialsProvider.<init>(Unknown Source)
jenkins-0 jenkins 
jenkins-0 jenkins Learn more:
jenkins-0 jenkins   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
jenkins-0 jenkins 
jenkins-0 jenkins 1 error
jenkins-0 jenkins 
jenkins-0 jenkins ======================
jenkins-0 jenkins Full classname legend:
jenkins-0 jenkins ======================
jenkins-0 jenkins SystemCredentialsProvider: "com.cloudbees.plugins.credentials.SystemCredentialsProvider"
jenkins-0 jenkins ========================
jenkins-0 jenkins End of classname legend:
jenkins-0 jenkins ========================
jenkins-0 jenkins 
jenkins-0 jenkins       at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
jenkins-0 jenkins       at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
jenkins-0 jenkins       at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
jenkins-0 jenkins       at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:448)
jenkins-0 jenkins       at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
jenkins-0 jenkins       at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
jenkins-0 jenkins       at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:406)
jenkins-0 jenkins       at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:397)
jenkins-0 jenkins       at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:335)
jenkins-0 jenkins       at hudson.ExtensionList.load(ExtensionList.java:384)
jenkins-0 jenkins       at hudson.ExtensionList.ensureLoaded(ExtensionList.java:320)
jenkins-0 jenkins       at hudson.ExtensionList.iterator(ExtensionList.java:172)
jenkins-0 jenkins       at hudson.ExtensionList.get(ExtensionList.java:149)
jenkins-0 jenkins       at com.cloudbees.plugins.credentials.SystemCredentialsProvider.getInstance(SystemCredentialsProvider.java:145)
jenkins-0 jenkins       at com.cloudbees.plugins.credentials.SystemCredentialsProvider.forceLoadDuringStartup(SystemCredentialsProvider.java:127)
jenkins-0 jenkins       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins-0 jenkins       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jenkins-0 jenkins       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jenkins-0 jenkins       at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
jenkins-0 jenkins       at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
jenkins-0 jenkins       at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
jenkins-0 jenkins       at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
jenkins-0 jenkins       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jenkins-0 jenkins       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.Thread.run(Unknown Source)
jenkins-0 jenkins 2024-06-10 13:32:52.936+0000 [id=31]  INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
jenkins-0 jenkins 2024-06-10 13:32:53.035+0000 [id=27]  INFO    jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
jenkins-0 jenkins 2024-06-10 13:32:53.036+0000 [id=27]  INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
jenkins-0 jenkins 2024-06-10 13:32:53.037+0000 [id=27]  INFO    hudson.WebAppMain#contextDestroyed: Shutting down a Jenkins instance that was still starting up
jenkins-0 jenkins java.lang.Throwable: reason
jenkins-0 jenkins       at hudson.WebAppMain.contextDestroyed(WebAppMain.java:407)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:1059)
jenkins-0 jenkins       at org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:636)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.ContextHandler.contextDestroyed(ContextHandler.java:1016)
jenkins-0 jenkins       at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:306)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
jenkins-0 jenkins       at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:412)
jenkins-0 jenkins       at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:413)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
jenkins-0 jenkins       at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:497)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:1039)
jenkins-0 jenkins       at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:399)
jenkins-0 jenkins       at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1311)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1087)
jenkins-0 jenkins       at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:312)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
jenkins-0 jenkins       at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
jenkins-0 jenkins       at org.eclipse.jetty.server.Server.doStop(Server.java:517)
jenkins-0 jenkins       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
jenkins-0 jenkins       at winstone.Launcher.shutdown(Launcher.java:442)
jenkins-0 jenkins       at winstone.ShutdownHook.run(ShutdownHook.java:28)
jenkins-0 jenkins 2024-06-10 13:32:53.041+0000 [id=24]  SEVERE  hudson.util.BootFailure#publish: Failed to initialize Jenkins
jenkins-0 jenkins java.lang.InterruptedException
jenkins-0 jenkins       at java.base/java.lang.Object.wait(Native Method)
jenkins-0 jenkins       at java.base/java.lang.Object.wait(Unknown Source)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:288)
jenkins-0 jenkins       at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
jenkins-0 jenkins       at jenkins.model.Jenkins.executeReactor(Jenkins.java:1210)
jenkins-0 jenkins       at jenkins.model.Jenkins.<init>(Jenkins.java:997)
jenkins-0 jenkins       at hudson.model.Hudson.<init>(Hudson.java:86)
jenkins-0 jenkins       at hudson.model.Hudson.<init>(Hudson.java:82)
jenkins-0 jenkins       at hudson.WebAppMain$3.run(WebAppMain.java:248)
jenkins-0 jenkins Caused: hudson.util.HudsonFailedToLoad
jenkins-0 jenkins       at hudson.WebAppMain$3.run(WebAppMain.java:276)
jenkins-0 jenkins 2024-06-10 13:32:53.054+0000 [id=31]  SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Queue.init
jenkins-0 jenkins java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
jenkins-0 jenkins       at jenkins.model.Jenkins.get(Jenkins.java:824)
jenkins-0 jenkins       at hudson.model.Queue.getXMLQueueFile(Queue.java:514)
jenkins-0 jenkins       at hudson.model.Queue.load(Queue.java:401)
jenkins-0 jenkins       at hudson.model.Queue.init(Queue.java:3092)
jenkins-0 jenkins Caused: java.lang.reflect.InvocationTargetException
jenkins-0 jenkins       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins-0 jenkins       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jenkins-0 jenkins       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jenkins-0 jenkins       at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
jenkins-0 jenkins Caused: java.lang.Error
jenkins-0 jenkins       at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:115)
jenkins-0 jenkins       at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
jenkins-0 jenkins       at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
jenkins-0 jenkins       at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
jenkins-0 jenkins       at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
jenkins-0 jenkins       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jenkins-0 jenkins       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.Thread.run(Unknown Source)
jenkins-0 jenkins 2024-06-10 13:32:53.050+0000 [id=27]  INFO    o.e.j.s.handler.ContextHandler#doStop: Stopped w.@4d8286c4{Jenkins v2.452.1,/,null,STOPPED}{/var/jenkins_cache/war}
jenkins-0 jenkins 2024-06-10 13:32:53.145+0000 [id=63]  SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (Download metadata thread/63) died unexpectedly due to an uncaught exception. This may leav
e your server corrupted and usually indicates a software bug.
jenkins-0 jenkins java.lang.ClassNotFoundException: hudson.model.AsyncPeriodicWork$LazyTaskListener
jenkins-0 jenkins       at java.base/java.net.URLClassLoader.findClass(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jenkins-0 jenkins       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jenkins-0 jenkins       at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:511)
jenkins-0 jenkins       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jenkins-0 jenkins Caused: java.lang.NoClassDefFoundError: hudson/model/AsyncPeriodicWork$LazyTaskListener
jenkins-0 jenkins       at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:99)
jenkins-0 jenkins       at java.base/java.lang.Thread.run(Unknown Source)
jenkins-0 jenkins 2024-06-10 13:32:53.151+0000 [id=27]  INFO    winstone.Logger#logInternal: Jetty shutdown successfully
jenkins-0 jenkins 2024-06-10 13:32:53.151+0000 [id=26]  INFO    winstone.Logger#logInternal: Control thread shutdown successfully

```

### Version of Helm and Kubernetes

```markdown
- ArgoCD 2.10.7 (which uses helm under the hood)
- Kubernetes v1.28.6+k3s2
```

### Chart version

5.1.28

### What happened?

```bash
1. Create ArgoCD application that uses the following values:


    - chart: jenkins
      repoURL: https://charts.jenkins.io
      targetRevision: 5.1.28
      helm:
        releaseName: jenkins
        values: |
          controller:
            jenkinsUrl: "https://redacted"
            admin:
              existingSecret: "jenkins-admin-password"
              userKey: jenkins-admin-user
              passwordKey: jenkins-admin-password
            javaOpts: '-Xms1000m -Xmx1000m'
            resources:
              requests:
                cpu: "250m"
                memory: "1024Mi"
              limits:
                cpu: "250m"
                memory: "1024Mi"
            initContainerEnv:
              - name: JAVA_OPTS
                value: -Xms1024m -Xmx2048m
            initContainerResources:
              requests:
                cpu: "250m"
                memory: "256Mi"
              limits:
                cpu: "250m"
                memory: "2048Mi"
```

2. Wait for the init containers to successfully finish
3. The Jenkins pod itself starts up, takes some time and then throws out the error message above.

I cannot rule out that the multiple failed restarts I had until the memory constraints were working somehow corrupted files. I'll try to remove everything and start from scratch.
```


### What you expected to happen?

_No response_

### How to reproduce it

_No response_

### Anything else we need to know?

_No response_

**Comment by avnerv** [comment]
hitting this as well
