### ISSUE TITLE
Jenkins build agent fails to run 

### ISSUE THREAD

**Issue by sanjaymp18** [jenkinsci/helm-charts#187]
I'm run Jenkins using helm 3 with very minimal changes in the values.yaml file, jenkins pods come up and after configuring the K8s cloud with secret credentials, while executing a simple job, the build agent pod is initiated and gets terminated, instantly.

helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

 kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Which version of the chart**:
helm list -n jenkins
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
jenkins jenkins         1               2020-12-10 23:15:26.919199579 +0530 IST deployed        jenkins-3.0.4   2.249.3

**What happened**:

When  I create a Job, dynamic build agent runs into error state and terminates
```
kubectl get all -n jenkins -o wide                                                        Fri Dec 11 00:11:40 2020

NAME                READY   STATUS    RESTARTS   AGE   IP            NODE                       NOMINATED NODE   READINESS GAT
ES
pod/default-vp0h9   0/1     Error     0          57m   10.244.1.73   vlab048.600.lab   <none>           <none>
pod/jenkins-0       2/2     Running   0          56m   10.244.1.74   vlab048.600.lab   <none>           <none>

NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE   SELECTOR
service/jenkins         NodePort    10.109.201.161   <none>        8080:32323/TCP   56m   app.kubernetes.io/component=jenkins-
controller,app.kubernetes.io/instance=jenkins
service/jenkins-agent   ClusterIP   10.109.91.109    <none>        50000/TCP        56m   app.kubernetes.io/component=jenkins-
controller,app.kubernetes.io/instance=jenkins

NAME                       READY   AGE   CONTAINERS              IMAGES
statefulset.apps/jenkins   1/1     56m   jenkins,config-reload   vlab04801.ab:5000/myjenkins:latest,kiwigrid/k8s-s
idecar:0.1.275
```

**What you expected to happen**:
should connect via jnlp and run fine.

**How to reproduce it** (as minimally and precisely as possible):

```
controller:
  # Used for label app.kubernetes.io/component
  componentName: "jenkins-controller"
  image: "vlab048.7600.lab:5000/myjenkins"
  tag: "latest"
  imagePullPolicy: "Always"

  adminUser: "admin"
  adminPassword: "admin"
  servicePort: 8080
  targetPort: 8080
  serviceType: NodePort
  nodePort: 32323
  installPlugins: []

  JCasC:
    defaultConfig: true
    configScripts: {}
    welcome-message: |
      jenkins:
        systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
    # Ignored if securityRealm is defined in controller.JCasC.configScripts and
    # ignored if controller.enableXmlConfig=true as controller.securityRealm takes precedence
    securityRealm: |-
      local:
        allowsSignup: false
serviceAccount:
 create: false

persistence:
  enabled: false
```
official jenkins image  with plugin preinstalled is being used
```
helm install jenkins jenkins/jenkins -f values.yaml -n jenkins
```

I removed `Command to run:/bin/sh -c` and `Arguments to pass to the command:${computer.jnlpmac} ${computer.name}` option from the pod template and then the pod didn't run into errors, but the jnlp connection timeout.
Jenkins pod provides the below logs when the build agent pod spawns:

```
2020-12-10 18:51:39.613+0000 [id=35]    INFO    o.c.j.p.k.KubernetesCloud#provision: Excess workload after pending Kubernetes agents: 1
2020-12-10 18:51:39.614+0000 [id=35]    INFO    o.c.j.p.k.KubernetesCloud#provision: Template for label null: default
2020-12-10 18:51:49.619+0000 [id=40]    INFO    hudson.slaves.NodeProvisioner#lambda$update$6: default-lws0j provisioning successfully completed. We have now 2 computer(s)
2020-12-10 18:51:49.623+0000 [id=88]    INFO    o.c.j.p.k.KubernetesLauncher#launch: Created Pod: jenkins/default-lws0j
2020-12-10 18:51:49.673+0000 [id=837]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-12-10 18:51:49.719+0000 [id=88]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-12-10 18:51:59.724+0000 [id=88]    WARNING o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: default-lws0j, template=PodTemplate{id='3e910edb-6073-4609-aa3b-0bf8752df48f'inheritFrom='', name='default', namespace='', hostNetwork=false, label='jenkins-jenkins-agent ', serviceAccount='default', nodeSelector='', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], containers=[ContainerTemplate{name='jnlp', image='jenkins/inbound-agent:4.6-1', workingDir='/home/jenkins', command='/bin/sh -c', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='512m', resourceRequestMemory='512Mi', resourceLimitCpu='512m', resourceLimitMemory='512Mi', envVars=[KeyValueEnvVar [getValue()=http://jenkins.svc.cluster.local:8080/, getKey()=JENKINS_URL]], livenessProbe=ContainerLivenessProbe{execArgs='', timeoutSeconds=0, initialDelaySeconds=0, failureThreshold=0, periodSeconds=0, successThreshold=0}}]}
java.lang.IllegalStateException: Pod has terminated containers: jenkins/default-lws0j (jnlp)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:133)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:154)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:94)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:156)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:296)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-12-10 18:51:59.725+0000 [id=88]    INFO    o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent default-lws0j
2020-12-10 18:51:59.732+0000 [id=88]    INFO    o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent jenkins/default-lws0j
2020-12-10 18:51:59.732+0000 [id=88]    INFO    o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer default-lws0j
Terminated Kubernetes instance for agent jenkins/default-lws0j
Disconnected computer default-lws0j


```

Build agent pod logs

```
kubectl logs -f default-vp0h9  -n jenkins
Dec 10, 2020 5:43:47 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: default-vp0h9
Dec 10, 2020 5:43:47 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Dec 10, 2020 5:43:47 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.6
Dec 10, 2020 5:43:47 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/remoting as a remoting work directory
Dec 10, 2020 5:43:47 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /home/jenkins/remoting
Dec 10, 2020 5:43:47 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://vlab048009.dom047600.lab:32323]
Dec 10, 2020 5:43:47 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Dec 10, 2020 5:43:47 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting TCP connection tunneling is enabled. Skipping the TCP Agent Listener Port availability check
Dec 10, 2020 5:43:47 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: vlab048009.dom047600.lab
  Agent port:    32001
  Identity:      31:a0:a1:bb:04:48:66:36:fa:08:3a:de:0c:68:34:cd
Dec 10, 2020 5:43:47 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Dec 10, 2020 5:43:47 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001
Dec 10, 2020 5:43:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:2)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:44:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:3)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:44:17 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:4)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:44:27 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:5)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:44:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:6)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:44:47 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:7)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:44:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:8)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:45:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:9)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:45:17 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:10)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:45:27 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to vlab048009.dom047600.lab:32001 (retrying:11)
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more

Dec 10, 2020 5:45:27 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to vlab048009.dom047600.lab:32001
java.io.IOException: Failed to connect to vlab048009.dom047600.lab:32001
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:248)
        at hudson.remoting.Engine.connectTcp(Engine.java:840)
        at hudson.remoting.Engine.innerRun(Engine.java:718)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:482)
        at sun.nio.ch.Net.connect(Net.java:474)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpoint.open(JnlpAgentEndpoint.java:206)
        ... 3 more


```

**Comment by sanjaymp18** [comment]
K8s cluster is running on 2 node (1 master and 1 worker) and agent specs are as below:

```
# Source: jenkins/templates/jenkins-agent-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: default
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-3.0.4"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
spec:
  ports:
    - port: 50000
      targetPort: 50000
      name: agent-listener
  selector:
    "app.kubernetes.io/component": "jenkins-controller"
    "app.kubernetes.io/instance": "jenkins"
  type: ClusterIP
```

I need to change the service type to `NodePort` and `targetPort:32001`,  by changing `agentListenerServiceType: "NodePort"` i could correct the first part how to change the `targetPort` for the agent ?
