### ISSUE TITLE
configuration-as-code plugin is the wrong version and crashing new and existing jenkins deployments

### ISSUE THREAD

**Issue by stewartshea** [jenkinsci/helm-charts#249]
**Describe the bug**

**Version of Helm and Kubernetes**:  
Kubernetes: v1.17.14-gke.1600
Helm: v3.5.0
Chart: v3.1.8

**What happened**:
This started just by reloading jenkins, which lead to uninstall/re-install for debugging which identified the issue as tied to any new deployment with the latest helm chart. When Jenkins starts, the main jenkins container will restart with the following errors: 

```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-02-11 13:51:54.140+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @1131ms to org.eclipse.jetty.util.log.JavaUtilLog
2021-02-11 13:51:54.398+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2021-02-11 13:51:54.468+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2021-02-11 13:51:54.673+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 1.8.0_242-b08
2021-02-11 13:51:55.334+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2021-02-11 13:51:55.561+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2021-02-11 13:51:55.562+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2021-02-11 13:51:55.564+0000 [id=1]     INFO    o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2021-02-11 13:51:56.685+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-02-11 13:51:57.032+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@18317edc{Jenkins v2.263.3,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2021-02-11 13:51:57.081+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@6be46e8f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-02-11 13:51:57.087+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started @4079ms
2021-02-11 13:51:57.093+0000 [id=21]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2021-02-11 13:51:59.530+0000 [id=28]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2021-02-11 13:51:59.899+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2021-02-11 13:51:59.929+0000 [id=26]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Credentials Plugin v2.3.15 (credentials)
java.io.IOException: Failed to load: Credentials Plugin (2.3.15)
 - Update required: Configuration as Code Plugin (1.46) to be updated to 1.47 or higher
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)

.....
....
2021-02-11 13:52:08.300+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2021-02-11 13:52:09.124+0000 [id=29]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
java.lang.IllegalArgumentException: No hudson.slaves.Cloud implementation found for kubernetes
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$lookupDescriptor$11(HeteroDescribableConfigurator.java:211)
        at io.vavr.control.Option.orElse(Option.java:321)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lookupDescriptor(HeteroDescribableConfigurator.java:210)
....
....
2021-02-11 13:52:09.471+0000 [id=20]    INFO    jenkins.model.Jenkins#cleanUp: Stopping Jenkins
2021-02-11 13:52:09.538+0000 [id=20]    INFO    jenkins.model.Jenkins$18#onAttained: Started termination
2021-02-11 13:52:09.595+0000 [id=20]    INFO    jenkins.model.Jenkins$18#onAttained: Completed termination
2021-02-11 13:52:09.595+0000 [id=20]    INFO    jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
2021-02-11 13:52:09.619+0000 [id=20]    INFO    jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
2021-02-11 13:52:09.632+0000 [id=20]    INFO    jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
2021-02-11 13:52:09.660+0000 [id=20]    INFO    jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
2021-02-11 13:52:09.661+0000 [id=20]    INFO    jenkins.model.Jenkins#cleanUp: Jenkins stopped
2021-02-11 13:52:40.903+0000 [id=22]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
```

**What you expected to happen**:
Jenkins should start up properly on the initial install without having to fuss with the plugins.txt configmap

**How to reproduce it** (as minimally and precisely as possible):

values.yml
```
persistence:
  enabled: true
```

```
helm repo add jenkinsci https://charts.jenkins.io
helm repo update
helm install jenkins -f values.yaml jenkinsci/jenkins
```

**Anything else we need to know: The Fix**:

Changing the plugin version in the configmap for the configuration-as-code plugin to "latest" or "1.47" seems to fix the issue. 

```
kubectl edit configmap jenkins

....
  plugins.txt: |-
    kubernetes:1.27.6
    workflow-aggregator:2.6
    git:4.5.2
    configuration-as-code:1.47
....

```

**Comment by stewartshea** [comment]
Looks like this was just fixed 30 minutes ago (while writing the issue)... Timing is everything! 

https://github.com/jenkinsci/helm-charts/pull/248
