### ISSUE TITLE
Datadog Log Shipper failing

### ISSUE THREAD

**Issue by djtecha** [jenkinsci/helm-charts#250]
Hello all, running the latest JENKINS and Datadog and the logging used to work shipping to a datadog agent running on the cluster. Now I just get this:
```
Feb 12, 2021 12:54:21 AM org.jenkinsci.plugins.workflow.log.TaskListenerDecorator$DecoratedTaskListener getLogger
WARNING: null
java.lang.NullPointerException
at org.datadog.jenkins.plugins.datadog.logs.DatadogTaskListenerDecorator.decorate(DatadogTaskListenerDecorator.java:53)
at org.jenkinsci.plugins.workflow.log.TaskListenerDecorator$DecoratedTaskListener.getLogger(TaskListenerDecorator.java:237)
at org.jenkinsci.plugins.workflow.log.TaskListenerDecorator$CloseableTaskListener.getLogger(TaskListenerDecorator.java:279)
at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1381)
at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1333)
at hudson.remoting.UserRequest.perform(UserRequest.java:211)
at hudson.remoting.UserRequest.perform(UserRequest.java:54)
at hudson.remoting.Request$2.run(Request.java:376)
at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
at java.lang.Thread.run(Thread.java:748)
```
datadog helm chart version: 2.8.3
jenkins helm chart version: 3.1.8

datadog plugin 2.8.1

**Comment by torstenwalter** [comment]
Opening an issue for datadog could be a better place to get help.
