### ISSUE TITLE
JCasC 'welcome-message' configuration example does not work

### ISSUE THREAD

**Issue by FNSdev** [jenkinsci/helm-charts#26]
Hi!

I am struggling with making an example of custom JCasC configuraion work.

My values.yaml

```
master:
  serviceType: ClusterIP
  servicePort: 8081
  installPlugins:
    - kubernetes:1.27.0
    - workflow-aggregator:2.6
    - workflow-job:2.39
    - git:4.4.1
    - configuration-as-code:1.41
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
    welcome-message: |
      jenkins:
        systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
  # https://github.com/helm/charts/issues/15453
  customInitContainers:
    - name: "volume-mount-permission"
      image: "busybox"
      command: ["/bin/chown", "-R", "1000", "/var/jenkins_home"]
      volumeMounts:
        - name: "jenkins-home"
          mountPath: "/var/jenkins_home"
      securityContext:
        runAsUser: 0
  jenkinsUriPrefix: "/jenkins"
persistence:
  storageClass: jenkins
  size: "4Gi"
```

securityRealm setting works fine, but systemMessage is not set.

I also tried to add 
```
    jenkins-url: |
      unclassified:
        location:
          url: https://example.com/jenkins
          adminAddress: examle@gmail.com
```
into JCasC section, but without any success.

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
helm version
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

**Comment by FNSdev** [comment]
I have changed my values.yaml like this
```
master:
  serviceType: ClusterIP
  servicePort: 8081
  installPlugins:
    - kubernetes:1.27.0
    - workflow-aggregator:2.6
    - workflow-job:2.39
    - git:4.4.1
    - configuration-as-code:1.41
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
    configScripts:
      jenkins-url: |
        unclassified:
          location:
            url: https://example.com/jenkins
            adminAddress: example@gmail.com
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
  # https://github.com/helm/charts/issues/15453
  customInitContainers:
    - name: "volume-mount-permission"
      image: "busybox"
      command: ["/bin/chown", "-R", "1000", "/var/jenkins_home"]
      volumeMounts:
        - name: "jenkins-home"
          mountPath: "/var/jenkins_home"
      securityContext:
        runAsUser: 0
  jenkinsUriPrefix: "/jenkins"
persistence:
  storageClass: jenkins
  size: "4Gi"
```

And now I have another issue:
```
io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/jenkins_home/casc_configs/jenkins-url.yaml  in /var/jenkins_home/casc_configs/jenkins-url.yaml, line 3, column 10:
        url: https://example.com/jenkins
             ^
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:139)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:52)
Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/jenkins_home/casc_configs/jenkins-url.yaml
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:56)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:150)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-04 06:18:34.325+0000 [id=19]	SEVERE	hudson.util.BootFailure#publish: Failed to initialize Jenkins
```

**Comment by larrycai** [comment]
those needs to be overwritten in `values.yaml` for helm chart since `jcasc-default-config.yaml` already have it.

for url, I guess it is set in ingress part, I guess you removed this in the sample above.

````
master:
    ingress:
        hostName: xxx
````

You can check inside your jenkins

````
$ kubectl exec -it $(kubectl get pods -l app.kubernetes.io/name=jenkins -o=jsonpath='{.items[0].metadata.name}') -c jenkins bash
$ cat $CASC_JENKINS_CONFIG/jcasc-default-config.yaml
````

**Comment by FNSdev** [comment]
@larrycai Thank you for the reply
I use custom ingress configuration

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - example.com
        - www.example.com
      secretName: tls
  rules:
    - host: example.com
      http:
        paths:
        - path: /jenkins
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 8081
    - host: www.example.com
      http:
        paths:
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8081
```

Is there no other way to configure hostName?

**Comment by torstenwalter** [comment]
jenkins.url template is defined in:

https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L51-L68

That should give you an idea which values you can set to configure it.

This template is then used to configure it via JCasC:
https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L159-L163

**Comment by FNSdev** [comment]
@torstenwalter 
Thank you! That is exactly what I was looking for. 
I'm sorry for being not attentive enough, just getting started with Jenkins.

Could you please also clarify why the example with `systemMessage` was not working for me?

Do I have to put it into `configScripts` section?

**Comment by torstenwalter** [comment]
Yes

**Comment by torstenwalter** [comment]
https://github.com/jenkinsci/helm-charts/issues/29 contains an example. I think we should add it in the README.

@FNSdev Would you like to create a PR for it?

**Comment by larrycai** [comment]
> jenkins.url template is defined in:
> 
> https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L51-L68
> 
> That should give you an idea which values you can set to configure it.
> 
> This template is then used to configure it via JCasC:
> https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L159-L163

This is very nice information, can you add this tip into documentation on how the mapping works, so when we are stuck somewhere, we know where to find the template to check by ourselves.

**Comment by FNSdev** [comment]
@torstenwalter 
Please take a look
https://github.com/jenkinsci/helm-charts/pull/32
