### ISSUE TITLE
Redeploying Jenkins Helm chart results in "SEVERE	jenkins.InitReactorRunner$1#onTaskFailed java.io.IOException: Failed to load plugins"

### ISSUE THREAD

**Issue by hasakura12** [jenkinsci/helm-charts#294]
**Describe the bug**
`IOException: Failed to load plugins` when re-deploying Jenkins container on K8s worker nodes (AWS EC2 with EFS mounted), despite plugins are stored persistently.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
Jenkins 3.1.2

**What happened**:
Jenkins helm chart was deployed in K8s worker node, which auto-mounts EFS from EC2 userdata script.
Jenkins use K8s Persistent Volume:

pvc.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 8Gi
```

pv.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: jenkins
spec:
  capacity:
    storage: 10Gi # this doesn't matter for EFS
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxx:/jenkins # make sure this is the correct EFS file systme ID. Can specify subpath (if EFS is mounted at /mnt/efs, and you want to specify subpath /mnt/efs/jenkins, just specify /jenkins, not /mnt/efs/jenkins). Ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/volume_path/README.md
    # volumeAttributes:
    #   encryptInTransit: "true"  # disable encryption in transit as jenkins helm spits error "MountVolume.SetUp failed for volume "jenkins" : rpc error: code = InvalidArgument desc = Volume context property encryptInTransit not supported"
```

overrides.yaml
```yaml
controller:
  # use Docker in Docker jenkins, so that jenkins container can build docker image inside
  # image: mesosphere/jenkins-dind # https://hub.docker.com/r/mesosphere/jenkins-dind
  # tag: 0.9.0
  statefulSetLabels:
    app: jenkins  # needed for istio
    version: 2.0.0  # needed for istio
  serviceLabels:
    app: jenkins  # needed for istio
    version: 2.0.0  # needed for istio
  podLabels:
    app: jenkins  # needed for istio
    version: 2.0.0  # needed for istio
  additionalPlugins: # WARNING: uncommenting out these will cause pod to crash due to "cp -r not specified". So for now, these plugins need be installed manually
    - matrix-auth:2.6.4
    # - kubernetes:1.25.7
    # - workflow-job:2.39
    # - workflow-aggregator:2.6
    # - credentials-binding:1.23
    # - git:4.2.2
    # - configuration-as-code:1.41
    # - bitbucket:.1.1.11 # https://plugins.jenkins.io/bitbucket/
    # - bitbucket-build-status-notifier:1.4.2 # https://plugins.jenkins.io/bitbucket-build-status-notifier/
    # - bitbucket-oauth:0.10
    # - docker-build-publish:1.554.2  # https://plugins.jenkins.io/docker-build-publish/
    # - amazon-ecr:1.6 # https://plugins.jenkins.io/amazon-ecr/
    # - slack:2.40 # https://plugins.jenkins.io/slack/
    # - blueocean:1.23.2 # https://plugins.jenkins.io/blueocean/
    # - disk-usage:0.28 # https://plugins.jenkins.io/disk-usage/
    # - ws-cleanup:0.38 # https://plugins.jenkins.io/ws-cleanup/
    # - timestamper:1.11.3 # https://plugins.jenkins.io/timestamper/
    # - build-timeout:1.20 # https://plugins.jenkins.io/build-timeout/

serviceAccount:
  name: jenkins
  # for Jenkins pod to assume IAM role (IRSA)
  annotations: 
    eks.amazonaws.com/role-arn: "arn:aws:iam::xxxx:role/EKSJenkinsRole"

persistence:
  existingClaim: jenkins-claim # efs csi driver doesn't support dynamic provisioning, so pv and pvc needs to be precreated. Ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver
  # storageClass: efs # use EFS storageclass. If the storage class is set to null or left undefined (persistence.storageClass=), the default provisioner is used (gp2 on AWS, standard on GKE, AWS & OpenStack).
  size: 8Gi
```

Install
```
helm install jenkins jenkins-3.1.2.tgz     -n jenkins     -f overrides.yaml
```

And Jenkins was working fine until I restarted K8s worker nodes (i.e. AWS EC2) because I needed to patch some vulnerable packages and restart the servers. I did `kubectl drain NODE_NAME` to move pods to other nodes, then manually terminated EC2, upon which AWS ASG kicks in and launch new K8s worker nodes.

After that, Jenkins container was in CrashLoopBack state.

```
kubectl get pod -n jenkins

NAME        READY   STATUS             RESTARTS
AGE
jenkins-0   1/2     CrashLoopBackOff   79
```

```sh
k describe po jenkins-0 -n jenkins

Containers:
  jenkins:
    Container ID:  docker://e201b68dc19ee951fbcdfa41103512a0e52941660540d7048d2254febd510c6e
    Image:         jenkins/jenkins:2.263.2
    Image ID:      docker-pullable://jenkins/jenkins@sha256:63fde6791bc9e11dc8fc94830ac76228afbe8d31206ab8f83f251314a3f45ba9
    Ports:         8080/TCP, 50000/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --httpPort=8080
    State:          Running
      Started:      Thu, 18 Mar 2021 03:25:53 +0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Thu, 18 Mar 2021 03:25:04 +0700
      Finished:     Thu, 18 Mar 2021 03:25:52 +0700
    Ready:          False
```

```
 k logs jenkins-0 -n jenkins -c jenkins 

Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-03-17 20:25:07.215+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @471ms to org.eclipse.jetty.util.log.JavaUtilLog
2021-03-17 20:25:07.393+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2021-03-17 20:25:07.437+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2021-03-17 20:25:07.532+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 1.8.0_242-b08
2021-03-17 20:25:08.350+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2021-03-17 20:25:08.409+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2021-03-17 20:25:08.409+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2021-03-17 20:25:08.411+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2021-03-17 20:25:08.980+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-03-17 20:25:09.109+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@18317edc{Jenkins v2.263.2,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2021-03-17 20:25:09.141+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@6be46e8f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-03-17 20:25:09.142+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @2398ms
2021-03-17 20:25:09.146+0000 [id=21]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2021-03-17 20:25:11.130+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2021-03-17 20:25:14.159+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2021-03-17 20:25:14.842+0000 [id=29]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Credentials Plugin v2.3.15 (credentials)
java.io.IOException: Failed to load: Credentials Plugin (2.3.15)
 - Update required: Configuration as Code Plugin (1.46) to be updated to 1.47 or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-17 20:25:14.851+0000 [id=27]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Plain Credentials Plugin v1.7 (plain-credentials)
java.io.IOException: Failed to load: Plain Credentials Plugin (1.7)
 - Failed to load: Credentials Plugin (2.3.15)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-17 20:25:14.853+0000 [id=27]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Input Step v2.12 (pipeline-input-step)
java.io.IOException: Failed to load: Pipeline: Input Step (2.12)
 - Failed to load: Credentials Plugin (2.3.15)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

However, what puzzles me is Jenkins plugins have been stored on AWS EFS persistently, regardless of EC2's lifecycle
```sh
[ec2-user@ip-10-1-xxx-xxx /]$ ls /mnt/efs/jenkins/plugins -al
total 166504
drwxrwxr-x 123 ec2-user ec2-user    22528 Mar 17 12:54 .
drwxr-xr-x  21 ec2-user root         6144 Mar 17 20:33 ..
drwxr-xr-x   7 ec2-user ec2-user     6144 Jan 22 14:37 ace-editor
-rwxrwxr-x   1 ec2-user ec2-user  4279042 Jan 22 13:35 ace-editor.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 ace-editor.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        4 Jan 22 13:36 ace-editor.jpi.version_from_image
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:36 apache-httpcomponents-client-4-api
-rw-r--r--   1 ec2-user ec2-user  1769549 Jan 22 13:35 apache-httpcomponents-client-4-api.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 apache-httpcomponents-client-4-api.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user       11 Jan 22 13:35 apache-httpcomponents-client-4-api.jpi.version_from_image
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:35 authentication-tokens
-rw-r--r--   1 ec2-user ec2-user    14687 Jan 22 13:35 authentication-tokens.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 authentication-tokens.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        4 Jan 22 13:36 authentication-tokens.jpi.version_from_image
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:35 authorize-project
-rwxrwxr-x   1 ec2-user ec2-user    74731 Jan 22 13:34 authorize-project.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 bitbucket
-rwxrwxr-x   1 ec2-user ec2-user 10733155 Jan 22 13:35 bitbucket.bak
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:37 bitbucket-build-status-notifier
-rwxrwxr-x   1 ec2-user ec2-user   532724 Jan 22 13:35 bitbucket-build-status-notifier.jpi
-rw-r--r--   1 ec2-user ec2-user    27151 Jan 22 17:13 bitbucket.jpi
drwxrwxr-x   5 ec2-user ec2-user     6144 Jan 22 13:36 bitbucket-oauth
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 bitbucket-oauth.jpi.disabled
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:38 blueocean-autofavorite
-rwxrwxr-x   1 ec2-user ec2-user    60849 Jan 22 13:35 blueocean-autofavorite.jpi
-rwxrwxr-x   1 ec2-user ec2-user    69613 Jan 22 13:36 blueocean.bak
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-bitbucket-pipeline
-rwxrwxr-x   1 ec2-user ec2-user  2455648 Jan 22 13:35 blueocean-bitbucket-pipeline.bak
-rw-r--r--   1 ec2-user ec2-user  1072045 Jan 22 17:13 blueocean-bitbucket-pipeline.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-commons
-rwxrwxr-x   1 ec2-user ec2-user    85124 Jan 22 13:35 blueocean-commons.bak
-rw-r--r--   1 ec2-user ec2-user    85160 Jan 22 17:12 blueocean-commons.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-config
-rwxrwxr-x   1 ec2-user ec2-user    60982 Jan 22 13:35 blueocean-config.bak
-rw-r--r--   1 ec2-user ec2-user    61153 Jan 22 17:13 blueocean-config.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-core-js
-rwxrwxr-x   1 ec2-user ec2-user  1075606 Jan 22 13:36 blueocean-core-js.bak
-rw-r--r--   1 ec2-user ec2-user  1075939 Jan 22 17:12 blueocean-core-js.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-dashboard
-rwxrwxr-x   1 ec2-user ec2-user  2744582 Jan 22 13:35 blueocean-dashboard.bak
-rw-r--r--   1 ec2-user ec2-user  2744987 Jan 22 17:12 blueocean-dashboard.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:35 blueocean-display-url
-rwxrwxr-x   1 ec2-user ec2-user   374811 Jan 22 13:35 blueocean-display-url.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-events
-rwxrwxr-x   1 ec2-user ec2-user  5201788 Jan 22 13:35 blueocean-events.bak
-rw-r--r--   1 ec2-user ec2-user    23867 Jan 22 17:13 blueocean-events.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-github-pipeline
-rwxrwxr-x   1 ec2-user ec2-user   115838 Jan 22 13:35 blueocean-github-pipeline.bak
-rw-r--r--   1 ec2-user ec2-user    70153 Jan 22 17:13 blueocean-github-pipeline.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-git-pipeline
-rwxrwxr-x   1 ec2-user ec2-user   841929 Jan 22 13:35 blueocean-git-pipeline.bak
-rw-r--r--   1 ec2-user ec2-user   319996 Jan 22 17:13 blueocean-git-pipeline.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-i18n
-rwxrwxr-x   1 ec2-user ec2-user    14680 Jan 22 13:35 blueocean-i18n.bak
-rw-r--r--   1 ec2-user ec2-user    14970 Jan 22 17:13 blueocean-i18n.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-jira
-rwxrwxr-x   1 ec2-user ec2-user  2023734 Jan 22 13:35 blueocean-jira.bak
-rw-r--r--   1 ec2-user ec2-user  2009079 Jan 22 17:13 blueocean-jira.jpi
-rw-r--r--   1 ec2-user ec2-user     8272 Jan 22 17:13 blueocean.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-jwt
-rwxrwxr-x   1 ec2-user ec2-user   259755 Jan 22 13:35 blueocean-jwt.bak
-rw-r--r--   1 ec2-user ec2-user   297609 Jan 22 17:12 blueocean-jwt.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-personalization
-rwxrwxr-x   1 ec2-user ec2-user   703727 Jan 22 13:35 blueocean-personalization.bak
-rw-r--r--   1 ec2-user ec2-user   704045 Jan 22 17:13 blueocean-personalization.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-pipeline-api-impl
-rwxrwxr-x   1 ec2-user ec2-user   238489 Jan 22 13:35 blueocean-pipeline-api-impl.bak
-rw-r--r--   1 ec2-user ec2-user   191121 Jan 22 17:12 blueocean-pipeline-api-impl.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-pipeline-editor
-rwxrwxr-x   1 ec2-user ec2-user  1104238 Jan 22 13:35 blueocean-pipeline-editor.bak
-rw-r--r--   1 ec2-user ec2-user  1058028 Jan 22 17:12 blueocean-pipeline-editor.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-pipeline-scm-api
-rwxrwxr-x   1 ec2-user ec2-user   301406 Jan 22 13:35 blueocean-pipeline-scm-api.bak
-rw-r--r--   1 ec2-user ec2-user   301443 Jan 22 17:12 blueocean-pipeline-scm-api.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-rest
-rwxrwxr-x   1 ec2-user ec2-user   101910 Jan 22 13:35 blueocean-rest.bak
drwxr-xr-x   6 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-rest-impl
-rwxrwxr-x   1 ec2-user ec2-user   504879 Jan 22 13:35 blueocean-rest-impl.bak
-rw-r--r--   1 ec2-user ec2-user   502738 Jan 22 17:12 blueocean-rest-impl.jpi
-rw-r--r--   1 ec2-user ec2-user   101968 Jan 22 17:12 blueocean-rest.jpi
drwxr-xr-x   6 ec2-user ec2-user     6144 Jan 22 17:17 blueocean-web
-rwxrwxr-x   1 ec2-user ec2-user  1412306 Jan 22 13:35 blueocean-web.bak
-rw-r--r--   1 ec2-user ec2-user  1412665 Jan 22 17:12 blueocean-web.jpi
drwxr-xr-x   6 ec2-user ec2-user     6144 Mar 16 17:43 bootstrap4-api
-rw-r--r--   1 ec2-user ec2-user   536011 Mar 16 17:42 bootstrap4-api.jpi
-rw-r--r--   1 ec2-user ec2-user        0 Mar 16 17:42 bootstrap4-api.jpi.pinned
-rw-r--r--   1 ec2-user ec2-user        8 Mar 16 17:42 bootstrap4-api.jpi.version_from_image
drwxr-xr-x   4 ec2-user ec2-user     6144 Mar 16 17:42 bouncycastle-api
-rw-r--r--   1 ec2-user ec2-user  5901557 Mar 16 17:42 bouncycastle-api.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Mar 16 17:42 bouncycastle-api.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        5 Mar 16 17:42 bouncycastle-api.jpi.version_from_image
drwxr-xr-x   5 ec2-user ec2-user     6144 Jan 22 14:36 branch-api
-rw-r--r--   1 ec2-user ec2-user   311970 Jan 22 13:35 branch-api.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 branch-api.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        6 Jan 22 13:36 branch-api.jpi.version_from_image
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:38 build-timeout
-rwxrwxr-x   1 ec2-user ec2-user    96417 Jan 22 13:35 build-timeout.jpi
drwxr-xr-x   4 ec2-user ec2-user     6144 Mar 16 17:43 checks-api
-rw-r--r--   1 ec2-user ec2-user    68342 Mar 16 17:42 checks-api.jpi
-rw-r--r--   1 ec2-user ec2-user        0 Mar 16 17:42 checks-api.jpi.pinned
-rw-r--r--   1 ec2-user ec2-user        6 Mar 16 17:42 checks-api.jpi.version_from_image
drwxr-xr-x   5 ec2-user ec2-user     6144 Jan 22 17:17 cloudbees-bitbucket-branch-source
-rwxrwxr-x   1 ec2-user ec2-user   483333 Jan 22 13:35 cloudbees-bitbucket-branch-source.bak
-rw-r--r--   1 ec2-user ec2-user   485156 Jan 22 17:13 cloudbees-bitbucket-branch-source.jpi
drwxr-xr-x   5 ec2-user ec2-user     6144 Jan 22 14:35 cloudbees-folder
-rw-r--r--   1 ec2-user ec2-user   223145 Jan 22 13:34 cloudbees-folder.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 cloudbees-folder.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        5 Jan 22 13:35 cloudbees-folder.jpi.version_from_image
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 14:38 command-launcher
-rwxrwxr-x   1 ec2-user ec2-user    38884 Jan 22 13:36 command-launcher.jpi
drwxr-xr-x   5 ec2-user ec2-user     6144 Jan 22 14:35 configuration-as-code
-rw-r--r--   1 ec2-user ec2-user  2333107 Jan 22 13:35 configuration-as-code.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 configuration-as-code.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        5 Jan 22 13:35 configuration-as-code.jpi.version_from_image
drwxr-xr-x   6 ec2-user ec2-user     6144 Mar 16 17:43 credentials
drwxr-xr-x   4 ec2-user ec2-user     6144 Jan 22 17:17 credentials-binding
-rwxrwxr-x   1 ec2-user ec2-user    81841 Jan 22 13:36 credentials-binding.bak
-rw-r--r--   1 ec2-user ec2-user    81761 Jan 22 17:13 credentials-binding.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Jan 22 13:35 credentials-binding.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        5 Jan 22 13:34 credentials-binding.jpi.version_from_image
-rw-r--r--   1 ec2-user ec2-user   958856 Mar 16 17:42 credentials.jpi
-rwxrwxr-x   1 ec2-user ec2-user        0 Mar 16 17:42 credentials.jpi.pinned
-rwxrwxr-x   1 ec2-user ec2-user        7 Mar 16 17:42 credentials.jpi.version_from_image
```

Also NullPointerException for Jenkins pipeline branches
```
2021-03-17 20:25:21.314+0000 [id=29]	WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class hudson.plugins.disk_usage.DiskUsageProjectActionFactory$DescriptorImpl$1 in file:/var/jenkins_home/plugins/disk-usage/WEB-INF/lib/disk-usage.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
2021-03-17 20:25:21.329+0000 [id=29]	WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class hudson.plugins.disk_usage.DiskUsageOvearallGraphGenerator$DiskUsageRecord$1 in file:/var/jenkins_home/plugins/disk-usage/WEB-INF/lib/disk-usage.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
2021-03-17 20:25:22.078+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2021-03-17 20:25:22.092+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2021-03-17 20:25:23.520+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2021-03-17 20:25:23.653+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2021-03-17 20:25:24.297+0000 [id=29]	WARNING	c.c.h.p.folder.AbstractFolder#loadChildren: could not load /var/jenkins_home/jobs/REPO_NAME/branches/master
java.lang.NullPointerException
	at jenkins.branch.Branch.getName(Branch.java:145)
	at jenkins.branch.MultiBranchProjectDescriptor$ChildNameGeneratorImpl.dirNameFromItem(MultiBranchProjectDescriptor.java:246)
	at jenkins.branch.MultiBranchProjectDescriptor$ChildNameGeneratorImpl.dirNameFromItem(MultiBranchProjectDescriptor.java:222)
	at com.cloudbees.hudson.plugins.folder.AbstractFolder.loadChildren(AbstractFolder.java:403)
	at com.cloudbees.hudson.plugins.folder.AbstractFolder.onLoad(AbstractFolder.java:559)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.onLoad(ComputedFolder.java:221)
	at jenkins.branch.MultiBranchProject.onLoad(MultiBranchProject.java:174)
	at org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject.onLoad(WorkflowMultiBranchProject.java:84)
	at hudson.model.Items.load(Items.java:371)
	at jenkins.model.Jenkins$14.run(Jenkins.java:3268)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

But Jenkins pipeline branches are also saved on EFS
```sh
[ec2-user@ip-10-1-xx-xx /]$ ls /mnt/efs/jenkins/jobs/REPO_NAME/branches/ -al
drwxr-xr-x 3 ec2-user ec2-user  6144 Mar 16 08:59 master
```

I redeloyed jenkins helm chart to no avail.

**What you expected to happen**:
Jenkins container starts up without error

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by nickyfoster** [comment]
Same issue here. Chart version 2.6.4

**Comment by hasakura12** [comment]
Was able to bypass the errors by adding 
```yaml
  JCasC:
    defaultConfig: false
```

in overrides.yaml

https://github.com/jenkinsci/kubernetes-operator/issues/126#issuecomment-539461440 gave me a hint about Config as a Code setting.
