### ISSUE TITLE
"No such property: docker for class" error

### ISSUE THREAD

**Issue by dfgrosso** [jenkinsci/helm-charts#306]
Greetings.

Not sure I'm in the right place to ask this but, here it goes:

I'm using jenkins chart v.1.9.5 with jenkins/jenkins:2.277.1-lts.

I use docker commands in my jenkins files like: docker.withRegistry() or docker.build().

These are the plugins I have in the chart:

  installPlugins:
    - kubernetes:1.29.2
    - workflow-job:2.40
    - workflow-aggregator:2.6
    - credentials-binding:1.24
    - git:4.6.0
    - gitea:1.2.1
    - blueocean:1.24.4
    - artifactory:3.10.5
    - pipeline-utility-steps:2.6.1

This worked fine for one year now but, today, I needed to do chart upgrade and now I get:

```
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: docker for class: dockerBuild
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at dockerBuild.call(dockerBuild.groovy:7)
```

while running this:

vars/dockerBuild.groovy

```
def call(String buildName, String appVersion) {
    // build and push image
    container('docker') {
        script {
            docker.withRegistry("https://${env.CONTAINER_REGISTRY_DOMAIN}", 'xxx-container-registry-creds') {

(...)
```

Can anyone help?

Regards,
Daniel

**Comment by dfgrosso** [comment]
Hello again.

Added the plugin "docker-workflow:1.26" and now it's working.

Can anyone help me understand why I've never needed to have this plugin before?

Thanks.

Regards,
Daniel
