### ISSUE TITLE
init1.groovy: 1: unexpected token : import @ line 1, column 66.

### ISSUE THREAD

**Issue by cmoulliard** [jenkinsci/helm-charts#315]
**Describe the bug**
The groovy script is not executed correctly when it is loaded during jenkins starts

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**: latest

**What happened**: 
```console
2021-04-08 08:27:33.697+0000 [id=28]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/init1.groovy
2021-04-08 08:27:33.708+0000 [id=28]	WARNING	j.util.groovy.GroovyHookScript#execute: Failed to run script file:/var/jenkins_home/init.groovy.d/..2021_04_08_08_23_40.902233872/init1.groovy
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/var/jenkins_home/init.groovy.d/..2021_04_08_08_23_40.902233872/init1.groovy: 1: unexpected token: import @ line 1, column 66.
   alJobDslSecurityConfiguration import jen
                                 ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:350)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:144)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:110)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:234)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:168)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:943)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:584)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:138)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:129)
	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:112)
	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1129)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**How to reproduce it** (as minimally and precisely as possible):

I filled the `initScripts` script like this within the `my-values.yaml` file

```
initScripts:
    - "import javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration
      import jenkins.model.GlobalConfiguration
      GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).useScriptSecurity=false
      GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).save()"
```

and deployed my chart like that

```
helm install jenkinsci jenkins/jenkins -n ci -f my-values.yaml
```

**Comment by cmoulliard** [comment]
the workaround is to add `\n` as I did hereafter

```
initScripts:
    - "import jenkins.plugins.git.GitSCMSource\n
       import org.jenkinsci.plugins.workflow.libs.LibraryConfiguration\n
       import org.jenkinsci.plugins.workflow.libs.GlobalLibraries\n
       import org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever\n
       \n
       def GIT_SHARED_LIB_REPO = \"https://gitlab.cee.redhat.com/snowdrop/jenkins-shared-lib.git\";\n
       def mytools = new LibraryConfiguration(\"snowdrop-lib\",\n
       new SCMSourceRetriever(new GitSCMSource(GIT_SHARED_LIB_REPO)));\n
       mytools.setDefaultVersion(\"main\");\n
       mytools.setAllowVersionOverride(true);\n
       mytools.setIncludeInChangesets(true);\n
       GlobalLibraries.get().setLibraries(Arrays.asList(mytools));"
    - "import javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration\n
    ...
 ```

- Can you then document that adding `\n` is needed for multilines groovy script ?
- Would it be possible to load the groovy scripts using groovy local files ?

**Comment by garethjevans** [comment]
Could you use a multiline block in the yaml (I've not tried this, just suggesting) e.g.

```
initScripts:
- |
  import jenkins.plugins.git.GitSCMSource
  import ...
```

**Comment by cmoulliard** [comment]
> Could you use a multiline block in the yaml (I've not tried this, just suggesting) e.g.

Many thanks fo the trick. That fixed the problem

**Comment by alexey-panopta** [comment]
None of this is working for me. I keep getting:
```
2021-04-13 04:34:01.797+0000 [id=31]	WARNING	i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
```

**Comment by alexey-panopta** [comment]
The same can be achieved with the following config:
```
controller:
  JCasC:
    configScripts:
      jcasc-security: |
        security:
          GlobalJobDslSecurityConfiguration:
            useScriptSecurity: false
```

**Comment by torstenwalter** [comment]
@cmoulliard can we close this as your problem seems to be solved?

**Comment by cmoulliard** [comment]
We can but that should be great to improve documentation as we still struggle to figure out how to configure correctly JCasC ;-)

**Comment by torstenwalter** [comment]
Do you want to create a PR for it? You know best what has been missing in the docs from your perspective.
