### ISSUE TITLE
Plugin load failure in helm chart 3.3.12

### ISSUE THREAD

**Issue by Spritekin** [jenkinsci/helm-charts#360]
**Describe the bug**
Jenkins fails to start du to plugin incompatibilities.

**Version of Helm and Kubernetes**:

Helm Version: 3.0
I run using Terraform Cloud using the latest helm provider.

Kubernetes Version: 1.18
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Which version of the chart**:
3.3.12

**What happened**:
The chart installed but jenkins fails to startup and enters a restart cycle. Now I understand the first two messages but the third one says to upgrade junit plugin from 1.3 to 1.29+ is weird.

```
> kubectl logs dev-jenkins-0 jenkins
...

2021-05-12 03:27:11.069+0000 [id=28]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Matrix Project Plugin v1.18 (matrix-project)
java.io.IOException: Failed to load: Matrix Project Plugin (1.18)
 - Update required: JUnit Plugin (1.3) to be updated to 1.29 or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.440+0000 [id=30]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Groovy v2.89 (workflow-cps)
java.io.IOException: Failed to load: Pipeline: Groovy (2.89)
 - Update required: JavaScript GUI Lib: ACE Editor bundle plugin (1.0.1) to be updated to 1.1 or higher
 - Update required: Pipeline: Supporting APIs (2.20) to be updated to 3.7 or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.442+0000 [id=30]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Shared Groovy Libraries v2.11 (workflow-cps-global-lib)
java.io.IOException: Failed to load: Pipeline: Shared Groovy Libraries (2.11)
 - Failed to load: Pipeline: Groovy (2.89)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.444+0000 [id=30]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Multibranch v2.20 (workflow-multibranch)
java.io.IOException: Failed to load: Pipeline: Multibranch (2.20)
 - Failed to load: Pipeline: Groovy (2.89)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.444+0000 [id=30]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline Graph Analysis Plugin v1.1 (pipeline-graph-analysis)
java.io.IOException: Failed to load: Pipeline Graph Analysis Plugin (1.1)
 - Failed to load: Pipeline: Groovy (2.89)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.445+0000 [id=30]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: REST API Plugin v2.10 (pipeline-rest-api)
java.io.IOException: Failed to load: Pipeline: REST API Plugin (2.10)
 - Failed to load: Pipeline Graph Analysis Plugin (1.1)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.450+0000 [id=30]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Stage View Plugin v2.10 (pipeline-stage-view)
java.io.IOException: Failed to load: Pipeline: Stage View Plugin (2.10)
 - Failed to load: Pipeline: REST API Plugin (2.10)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.451+0000 [id=30]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Lockable Resources plugin v2.3 (lockable-resources)
java.io.IOException: Failed to load: Lockable Resources plugin (2.3)
 - Failed to load: Matrix Project Plugin (1.18)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.452+0000 [id=31]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Docker Pipeline v1.14 (docker-workflow)
java.io.IOException: Failed to load: Docker Pipeline (1.14)
 - Failed to load: Pipeline: Groovy (2.89)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.453+0000 [id=29]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Declarative Extension Points API v1.7.2 (pipeline-model-extensions)
java.io.IOException: Failed to load: Pipeline: Declarative Extension Points API (1.7.2)
 - Failed to load: Pipeline: Groovy (2.89)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.453+0000 [id=29]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Declarative Agent API v1.1.1 (pipeline-model-declarative-agent)
java.io.IOException: Failed to load: Pipeline: Declarative Agent API (1.1.1)
 - Failed to load: Pipeline: Declarative Extension Points API (1.7.2)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.454+0000 [id=29]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Declarative v1.3.2 (pipeline-model-definition)
java.io.IOException: Failed to load: Pipeline: Declarative (1.3.2)
 - Failed to load: Pipeline: Shared Groovy Libraries (2.11)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-12 03:27:11.455+0000 [id=29]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline v2.6 (workflow-aggregator)
java.io.IOException: Failed to load: Pipeline (2.6)
 - Failed to load: Lockable Resources plugin (2.3)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-05-12 03:27:24.357+0000 [id=22]	INFO	jenkins.model.Jenkins#cleanUp: Stopping Jenkins
2021-05-12 03:27:24.422+0000 [id=22]	INFO	jenkins.model.Jenkins$18#onAttained: Started termination
2021-05-12 03:27:24.433+0000 [id=22]	INFO	jenkins.model.Jenkins$18#onAttained: Completed termination
2021-05-12 03:27:24.433+0000 [id=22]	INFO	jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
2021-05-12 03:27:24.443+0000 [id=22]	INFO	jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
2021-05-12 03:27:24.521+0000 [id=22]	INFO	jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
2021-05-12 03:27:24.527+0000 [id=22]	INFO	jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
2021-05-12 03:27:24.530+0000 [id=22]	INFO	jenkins.model.Jenkins#cleanUp: Jenkins stopped
```

**What you expected to happen**:
Start with no conflicts in a barebones install.

**How to reproduce it** (as minimally and precisely as possible):
Install the chart clean.
```
################################################################################################################################################
## Install Jenkins
locals {
  jenkins_config = <<EOF
  controller:
    adminUser: ${var.jenkins_admin_user}
    adminPassword: ${var.jenkins_admin_password}

    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: my-ingress-class
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ssl-redirect: "true"
      hostName: jenkins.${local.environment_domain}
    serviceLabels:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    resources:
    prometheus:
      enabled: true
      serviceMonitorAdditionalLabels:
        release: prometheus-stack
      scrapeInterval: 60s
      scrapeEndpoint: /prometheus
      alertingRulesAdditionalLabels: {}
      alertingrules: []
    javaOpts: >
      -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true
    jenkinsUrl: jenkins.my.domain.com

  EOF 
}

resource "helm_release" "jenkins" {
  name       = "dev"
  repository = "https://charts.jenkins.io"
  chart      = "jenkins"
  version    = "3.3.12"

  values = [
    local.jenkins_config,        <<<<< configuration above
    var.jenkins_config_yaml  <<<< one simple job configured using jcasc
  ]
}
```

**Anything else we need to know**:
I cleaned up the messages and got this dependency tree
```Update required: JavaScript GUI Lib: ACE Editor bundle plugin (1.0.1) to be updated to 1.1 or higher
Update required: Pipeline: Supporting APIs (2.20) to be updated to 3.7 or higher
  Failed to load: Pipeline: Groovy (2.89)
    Failed to load: Pipeline: Declarative Extension Points API (1.7.2)
      Failed to load: Pipeline: Declarative Agent API (1.1.1)
    Failed to load: Docker Pipeline (1.14)
    Failed to load: Pipeline Graph Analysis Plugin (1.1)
      Failed to load: Pipeline: REST API Plugin (2.10)
        Failed to load: Pipeline: Stage View Plugin (2.10)
    Failed to load: Pipeline: Shared Groovy Libraries (2.11)
      Failed to load: Pipeline: Declarative (1.3.2)
    Failed to load: Pipeline: Multibranch (2.20)

Update required: JUnit Plugin (1.3) to be updated to 1.29 or higher ?????????????????????
  Failed to load: Matrix Project Plugin (1.18)
    Failed to load: Lockable Resources plugin (2.3)
      Failed to load: Pipeline (2.6)
```

Also I have uninstalled everything and checked no jenkins resources in the cluster before installing again. Same problem.
I connected to the jenkins container in the pod while it was running (before kube shuts it down) and went into the plugins folder... all the versions are there.

I tried to use the installPlugins parameter to add the updated plugins to latest versions but it keeps printing the same messages.

I'm stuck  on this. Please help.

Regards,

**Comment by Spritekin** [comment]
FYI, I managed to fix this by defining all the plugins to latest versions:
```
  installPlugins:
    - kubernetes:1.29.4
    - workflow-aggregator:2.6
    - git:4.7.1
    - configuration-as-code:1.51
    - workflow-cps:2.90
    - ace-editor:1.1
    - workflow-support:3.8
    - junit:1.49
    - pipeline-model-api:1.8.4
    - credentials-binding:1.24
  additionalPlugins:
    - prometheus:2.0.8
    - job-dsl:1.77
```
But its a really weird behaviour.
