### ISSUE TITLE
Getting java.lang.IllegalArgumentException: No hudson.security.SecurityRealm implementation found for activeDirectory 

### ISSUE THREAD

**Issue by diegoturcios** [jenkinsci/helm-charts#536]
**Describe the bug**
I had my configuration for active directory and it was working. Now I'm getting this error:
`java.lang.IllegalArgumentException: No hudson.security.SecurityRealm implementation found for activeDirector`

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Which version of the chart**:
```
  name: jenkins
  version: 3.10.3
  repository: https://charts.jenkins.io
```

**What happened**:
I'm trying run my active directory configuration.
Please see below:
```
jenkins:
  controller:
    JCasC:
      configScripts:
        security-realm: |-
          jenkins:
            authorizationStrategy:
              loggedInUsersCanDoAnything:
                allowAnonymousRead: false
            securityRealm:
              activeDirectory:
                startTls: true
                groupLookupStrategy: "AUTO"
                removeIrrelevantGroups: false
                domains:
                  - name: "XX.XXXXXXX.COM"
                    servers: "XX.XX.XX.X:XXXX"
                    bindName: ${ad_username}
                    site: "XXX.XXXXXXXXX.XXX; XXX"
                    bindPassword: ${ad_password}
                    tlsConfiguration: JDK_TRUSTSTORE

```
Yes, the secret is configured. I have check the config map and is well configure.

But I'm getting this error:
```
at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-14 01:33:07.996+0000 [id=15]	INFO	i.j.p.casc.TokenReloadAction#doIndex: Configuration reload triggered via token
2022-01-14 01:33:08.002+0000 [id=15]	WARNING	o.e.j.s.h.ContextHandler$Context#log: Error while serving http://localhost:8080/reload-configuration-as-code/
java.lang.IllegalArgumentException: No hudson.security.SecurityRealm implementation found for activeDirectory
at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$lookupDescriptor$11(HeteroDescribableConfigurator.java:211)
at io.vavr.control.Option.orElse(Option.java:321)
at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lookupDescriptor(HeteroDescribableConfigurator.java:210)
at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:84)
at io.vavr.Tuple2.apply(Tuple2.java:238)
at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:350)
at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)
at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:776)
at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:712)
at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:776)
at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:761)
at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:637)
at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:306)
at io.jenkins.plugins.casc.TokenReloadAction.doIndex(TokenReloadAction.java:58)
at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:393)
```

**What you expected to happen**:
This configuration should work and configure active directory.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
Do you have a plugin for active directory installed?
