### ISSUE TITLE
Jenkins InitContainer : Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by survivant** [jenkinsci/helm-charts#537]
Today Jenkins is not able to deploy correctly.

I use this ServiceAccount
````
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: jenkins
rules:
- apiGroups:
  - '*'
  resources:
  - statefulsets
  - services
  - replicationcontrollers
  - replicasets
  - podtemplates
  - podsecuritypolicies
  - pods
  - pods/log
  - pods/exec
  - podpreset
  - poddisruptionbudget
  - persistentvolumes
  - persistentvolumeclaims
  - jobs
  - endpoints
  - deployments
  - deployments/scale
  - daemonsets
  - cronjobs
  - configmaps
  - namespaces
  - events
  - secrets
  verbs:
  - create
  - get
  - watch
  - delete
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:jenkins
````

I used this values.yaml

````
controller:
  serviceType: NodePort
  nodePort: 30002

  adminPassword: admin

  # List of plugins to be install during Jenkins controller start
  installPlugins:
    - kubernetes:1.31.1
    - workflow-aggregator:2.6
    - git:4.10.1
    - configuration-as-code:1.55.1
    - generic-webhook-trigger:1.79
    - pipeline-utility-steps:2.11.0
    - ws-cleanup:0.40
    - bitbucket:214.v2fd4234d0554
    - cloudbees-bitbucket-branch-source:746.v350d2781c184

persistence:
  enabled: false

## Install Default RBAC roles and bindings
rbac:
  create: false

serviceAccount:
  create: false
  # The name of the service account is autogenerated by default
  name: jenkins
````

and I installed it with this command line 

````
     helm repo add jenkins https://charts.jenkins.io
     helm repo update

     kubectl create ns jenkins --dry-run=client -o yaml | kubectl apply -f -
   
     kubectl apply -f "./jenkins-sa.yaml"

    helm upgrade jenkins -n jenkins --install -f "./jenkins-values.yaml" jenkins/jenkins
````

Here the error in the logs
````
sdionne-test-1:~/ansible-iep/install-jenkins$ sudo kubectl -n jenkins logs jenkins-0 -c init
disable Setup Wizard
download plugins
File containing list of plugins to be downloaded: /var/jenkins_home/plugins.txt
Reading in plugins from /var/jenkins_home/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
Will use war file: /usr/share/jenkins/jenkins.war

Retrieving update center information
Update center URL: https://updates.jenkins.io/update-center.json?version=2.319.1
Cache miss for: update-center-2.319.1
io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:790)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:812)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:207)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:171)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:70)
Caused by: java.net.UnknownHostException: updates.jenkins.io
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:784)
        ... 4 more
Error getting update center json
````

````
vagrant@k8s-master:/vagrant/install-jenkins$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
````
````
sdionne-test-1:~/ansible-iep/install-jenkins$ uname -a
Linux sdionne-test-1 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
comact@sdionne-test-1:~/ansible-iep/install-jenkins$
````

if I try with curl
````
comact@sdionne-test-1:~/ansible-iep/install-jenkins$ curl  https://updates.jenkins.io/update-center.json?version=2.319.1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://updates.jenkins.io/dynamic-stable-2.319.1/update-center.json">here</a>.</p>
</body></html>
comact@sdionne-test-1:~/ansible-iep/install-jenkins$
````

if I try with the redirect
````
curl https://updates.jenkins.io/dynamic-stable-2.319.1/update-center.json

the output in OK...

````

maybe ``Jenkins CLI`` doesn't support the redirect ?

**Comment by survivant** [comment]
I changed the initContainer Init to use the URL (https://updates.jenkins.io/dynamic-stable-2.319.1/update-center.json) in a environment variable but I still got the problem

````
 initContainers:
      - command:
        - sh
        - /var/jenkins_config/apply_config.sh
        image: jenkins/jenkins:2.319.1-jdk11
        imagePullPolicy: Always
        name: init
        env:
        - name: JENKINS_UC
          value: https://updates.jenkins.io/dynamic-stable-2.319.1/update-center.json
....
````

````
disable Setup Wizard
download plugins
File containing list of plugins to be downloaded: /var/jenkins_home/plugins.txt
Reading in plugins from /var/jenkins_home/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/dynamic-stable-2.319.1/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
Will use war file: /usr/share/jenkins/jenkins.war

Retrieving update center information
Update center URL: https://updates.jenkins.io/dynamic-stable-2.319.1/update-center.json?version=2.319.1
Cache miss for: update-center-2.319.1
io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:790)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:812)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:207)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:171)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:70)
Caused by: java.net.UnknownHostException: updates.jenkins.io
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:784)
        ... 4 more
Error getting update center json
comact@sdionne-test-1:~/ansible-iep/install-jenkins$
````


Here the new statefulset
````
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: jenkins
    meta.helm.sh/release-namespace: jenkins
  creationTimestamp: "2022-01-14T16:50:10Z"
  generation: 1
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-3.10.2
  name: jenkins
  namespace: jenkins
  resourceVersion: "1740"
  uid: 28f69742-8e1d-4c8a-b782-2ef19331fcf0
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: jenkins-controller
      app.kubernetes.io/instance: jenkins
  serviceName: jenkins
  template:
    metadata:
      annotations:
        checksum/config: a311b21b3e59dfa46f3e64f7de0f66127a3787a50bc6d82bccf7453ca48f4ad8
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: jenkins-controller
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: jenkins
    spec:
      containers:
      - args:
        - --httpPort=8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: '-Dcasc.reload.token=$(POD_NAME) '
        - name: JENKINS_OPTS
          value: '--webroot=/var/jenkins_cache/war '
        - name: JENKINS_SLAVE_AGENT_PORT
          value: "50000"
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/casc_configs
        image: jenkins/jenkins:2.319.1-jdk11
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: agent-listener
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsUser: 1000
        startupProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
          readOnly: true
        - mountPath: /usr/share/jenkins/ref/plugins/
          name: plugin-dir
        - mountPath: /var/jenkins_home/casc_configs
          name: sc-config-volume
        - mountPath: /run/secrets/chart-admin-username
          name: admin-secret
          readOnly: true
          subPath: jenkins-admin-user
        - mountPath: /run/secrets/chart-admin-password
          name: admin-secret
          readOnly: true
          subPath: jenkins-admin-password
        - mountPath: /var/jenkins_cache
          name: jenkins-cache
        - mountPath: /tmp
          name: tmp-volume
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: LABEL
          value: jenkins-jenkins-config
        - name: FOLDER
          value: /var/jenkins_home/casc_configs
        - name: NAMESPACE
          value: jenkins
        - name: REQ_URL
          value: http://localhost:8080/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)
        - name: REQ_METHOD
          value: POST
        - name: REQ_RETRY_CONNECT
          value: "10"
        image: kiwigrid/k8s-sidecar:1.14.2
        imagePullPolicy: IfNotPresent
        name: config-reload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home/casc_configs
          name: sc-config-volume
        - mountPath: /var/jenkins_home
          name: jenkins-home
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - /var/jenkins_config/apply_config.sh
        image: jenkins/jenkins:2.319.1-jdk11
        imagePullPolicy: Always
        name: init
        env:
        - name: JENKINS_UC
          value: https://updates.jenkins.io/dynamic-stable-2.319.1/update-center.json

        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
        - mountPath: /usr/share/jenkins/ref/plugins
          name: plugins
        - mountPath: /var/jenkins_plugins
          name: plugin-dir
        - mountPath: /tmp
          name: tmp-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: plugins
      - configMap:
          defaultMode: 420
          name: jenkins
        name: jenkins-config
      - emptyDir: {}
        name: plugin-dir
      - emptyDir: {}
        name: jenkins-cache
      - emptyDir: {}
        name: jenkins-home
      - emptyDir: {}
        name: sc-config-volume
      - emptyDir: {}
        name: tmp-volume
      - name: admin-secret
        secret:
          defaultMode: 420
          secretName: jenkins
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: jenkins-7c86d68f57
  observedGeneration: 1
  replicas: 1
  updateRevision: jenkins-7c86d68f57
  updatedReplicas: 1
````

**Comment by survivant** [comment]
I think it was a network issue on my side.  I didn't find the reason, but sometimes the starting give that error and other times not.
