### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: not ready after 5000 MILLISECONDS 

### ISSUE THREAD

**Issue by rg970197** [jenkinsci/helm-charts#555]
### Describe the bug

This is happening in my 4 Jenkins servers after upgrading Jenkins and AKS.

`Af of sudden all Jenkins agent pods started giving Errors as below, Few pods are working and few are giving Errors. This is Happening 1-2 times out of 4-5 attempts.

AKS Version : 1.20.13

Jenkins Version, which clusters is having different version. I can reproduce this Error in all versions.

AKS-1:
kubernetes:1.30.1
kubernetes-client-api:5.10.1-171.vaa0774fb8c20
kubernetes-credentials:0.8.0

AKS-2:
kubernetes:1.31.3
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0

AKS-3:
kubernetes:1.30.1
kubernetes-client-api:5.10.1-171.vaa0774fb8c20
kubernetes-credentials:0.8.0

AKS-4:
kubernetes:1.31.3
workflow-job:1145.v7f2433caa07f
workflow-aggregator:2.6`

Troubleshooting steps i did.

revert Jenkins to old version => results in same Error
upgrade Jenkins to all new Version including plugins in use => Results in same Error.
Downgraded Jenkins K8s and K8s API plugins to stable version as per some suggestion in github. => same Error
Created Brand new cluster and install Jenkins and Job pod starting giving same Error. => same Error
Not sure how to resolve this Error. Please let me know if i'm missing anything.

### Version of Helm and Kubernetes

```markdown
- Helm: version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
- Kubernetes: 1.20.13 , 1.21.7
```

### Chart version

jenkins-3.11.3

### What happened?

```bash
1. Agent are pods are failing with io.fabric8.kubernetes.client.KubernetesClientException: not ready after 50000 MILLISECONDS
2. increased timeout and got io.fabric8.kubernetes.client.KubernetesClientException: not ready after 70000 MILLISECONDS
3.
...

Error: 
18:23:33  [WS-CLEANUP] Deleting project workspace...
18:23:33  [WS-CLEANUP] Deferred wipeout is used...
18:23:33  [WS-CLEANUP] done
18:23:33  [Pipeline] }
18:23:33  [Pipeline] // container
18:23:33  [Pipeline] }
18:23:33  [Pipeline] // node
18:23:33  [Pipeline] }
18:23:33  [Pipeline] // timeout
18:23:33  [Pipeline] }
18:23:33  [Pipeline] // podTemplate
18:23:33  [Pipeline] End of Pipeline
18:23:33  io.fabric8.kubernetes.client.KubernetesClientException: not ready after 5000 MILLISECONDS
18:23:33  	at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:176)
18:23:33  	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:322)
18:23:33  	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:84)
18:23:33  	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.doLaunch(ContainerExecDecorator.java:413)
18:23:33  	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.launch(ContainerExecDecorator.java:330)
18:23:33  	at hudson.Launcher$ProcStarter.start(Launcher.java:507)
18:23:33  	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:176)
18:23:33  	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:132)
18:23:33  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:324)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:319)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:193)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
18:23:33  	at jdk.internal.reflect.GeneratedMethodAccessor6588.invoke(Unknown Source)
18:23:33  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:23:33  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:23:33  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
18:23:33  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
18:23:33  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
18:23:33  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
18:23:33  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
18:23:33  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
18:23:33  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
18:23:33  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
18:23:33  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:158)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
18:23:33  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
18:23:33  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
18:23:33  	at WorkflowScript.run(WorkflowScript:114)
18:23:33  	at ___cps.transform___(Native Method)
18:23:33  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
18:23:33  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
18:23:33  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
18:23:33  	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
18:23:33  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:23:33  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:23:33  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
18:23:33  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
18:23:33  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
18:23:33  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
18:23:33  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
18:23:33  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
18:23:33  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
18:23:33  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:402)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:314)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:278)
18:23:33  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
18:23:33  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
18:23:33  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
18:23:33  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
18:23:33  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
18:23:33  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
18:23:33  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
18:23:33  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
18:23:33  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
18:23:33  	at java.base/java.lang.Thread.run(Thread.java:829)
18:23:33  [Bitbucket] Notifying commit build result
18:23:33  [Bitbucket] Build result notified
18:23:33  Finished: FAILURE
```

### What you expected to happen?

Successful build

**Comment by PhotoTeeborChoka** [comment]
The problem hits us as well. Returning to previous helm charts does not help. Restoring backups does not help. No matter the timeout, connection cannot be established.

This happens for every task that uses an explicitly created container in the job, specifically in the `container() {}` section.

This issue can be correlated with this: https://issues.jenkins.io/projects/JENKINS/issues/JENKINS-67664?filter=allopenissues

I could not find any remedy, what seems to be the problem? Has the jenkins agent code changed?

Has anybody found a solution/workaround?

**Comment by PhotoTeeborChoka** [comment]
Thank you, I will spin up a testing environment and confirm whether the issues persist when the version with the original agent is used.

**Comment by PhotoTeeborChoka** [comment]
The testing environment does not exhibit these issues. I created a new deployment using the same configuration and values for the jenkins helm the first one was used, but with a new empty volume. Everything worked fine. This leads me to the conclusion, that the issue likely lies in the shared volume that somehow gets corrupted on updates.

**Comment by lemeurherve** [comment]
> The problem hits us as well. Returning to previous helm charts does not help. Restoring backups does not help. No matter the timeout, connection cannot be established.
> 
> This happens for every task that uses an explicitly created container in the job, specifically in the `container() {}` section.
> 
> This issue can be correlated with this: [issues.jenkins.io/projects/JENKINS/issues/JENKINS-67664?filter=allopenissues](https://issues.jenkins.io/projects/JENKINS/issues/JENKINS-67664?filter=allopenissues)
> 
> I could not find any remedy, what seems to be the problem? Has the jenkins agent code changed?
> 
> Has anybody found a solution/workaround?

In our case, we've switched back to a single-container model as per https://support.cloudbees.com/hc/en-us/articles/360054642231-Considerations-for-Kubernetes-Clients-Connections-when-using-Kubernetes-Plugin for jenkins-infra.

See https://issues.jenkins.io/browse/JENKINS-67474

**Comment by edgarkz** [comment]
Any updates, please?
we have a similar issue with timeouts sometimes we get `not ready after 5000 MILLISECONDS` in our pipelines
Version [Jenkins 2.319.2]
K8S version  - EKS 1.19

**Comment by usulkies** [comment]
We also experience such exceptions, even after timeout increased to 70000 ms.

**Comment by PhotoTeeborChoka** [comment]
In our case, the issues never appeared in a clean deployment, i.e. a new deployment, into which non-plugin related data was restored. It looks as if the plugin updates and helm deployment collided in some way. Anyways, I suggest you set up an update procedure for Jenkins, in which you backup the jobs + secret data, deploy anew and restore the data. Works 100% of the time.

**Comment by pdp10** [comment]
We have the same problem. Really frustrating.

**Comment by timja** [comment]
The helm chart is not the place to discuss this.

See here instead https://issues.jenkins.io/browse/JENKINS-67664
