### ISSUE TITLE
SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin X (X)

### ISSUE THREAD

**Issue by mc-zact** [jenkinsci/helm-charts#629]
### Describe the bug

we're seeing eports of this here but I Can't fix it by setting all version to latest or setting JCasC to false

We see errors like this for all plugins pretty much:

SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Google Container Registry Auth Plugin v0.3 (google-container-registry-auth)

I've tried to set all version to latest:

```
    JCasC:
      defaultConfig: false
    installPlugins:
      - kubernetes:3580.v78271e5631dc
    additionalPlugins:
      - workflow-aggregator:578.vf9a_f99755f4a_
      - workflow-cps:2692.v76b_089ccd026
      - git:4.11.3
      - configuration-as-code:1429.v09b_044a_c93de
      - blueocean:1.25.5
  ```

Still get tons of SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin and jenkins container fails to start

### Version of Helm and Kubernetes

```markdown
- Helm: v3.9.0
- Kubernetes: 1.24 (kubectl)
```

### Chart version

jenkins-4.1.1

### What happened?

```bash
1. Jenkins stopped with the issue described above
2. Bumped to the latest chart and plugin versions
3. Issue still happens.
...
```

### What you expected to happen?

This issue appears to be common, so at most with updating to the latest plugin versions I was hopping it would fix this.

I also fully delete the deployment and re-deployed, sitll see:

```
Running from: /usr/share/jenkins/jenkins.war
2022-05-21 00:45:49.748+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @689ms to org.eclipse.jetty.util.log.JavaUtilLog
2022-05-21 00:45:49.886+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2022-05-21 00:45:49.932+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-05-21 00:45:50.025+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.46.v20220331; built: 2022-03-31T16:38:08.030Z; git: bc17a0369a11ecf40bb92c839b9ef0a8ac50ea18; jvm 11.0.15+10
2022-05-21 00:45:50.448+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2022-05-21 00:45:50.513+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2022-05-21 00:45:50.513+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2022-05-21 00:45:50.514+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2022-05-21 00:45:51.216+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-05-21 00:45:51.542+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@2392212b{Jenkins v2.348,/,file:///var/jenkins_cache/war/,AVAILABLE}{/var/jenkins_cache/war}
2022-05-21 00:45:51.592+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@54d9d12d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-05-21 00:45:51.592+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @2535ms
2022-05-21 00:45:51.593+0000 [id=23]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2022-05-21 00:45:51.895+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2022-05-21 00:45:52.202+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2022-05-21 00:45:52.227+0000 [id=31]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jackson 2 API Plugin v2.13.3-285.vc03c0256d517 (jackson2-api)
java.io.IOException: Failed to load: Jackson 2 API Plugin (jackson2-api 2.13.3-285.vc03c0256d517)
 - Update required: JAXB plugin (jaxb 2.3.0.1) to be updated to 2.3.6-1 or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:994)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:542)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1158)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:222)
```

this repeats for all plugins....

**Comment by timja** [comment]
You probably need to add `jaxb:2.3.6-1` to your list of plugins

**Comment by mc-zact** [comment]
Actually I had to get into the Jenkins container as root and wipe the plugins dir.

Even commenting out all plugins wouldn't work.


But I'm curious why would I need to set that one when I never had too?

**Comment by timja** [comment]
It’s because Jaxb is a detached plugin that was installed automatically for you and wasn’t explicitly in your plugin list, Jackson started requiring a new version than what you had before

**Comment by mc-zact** [comment]
> It’s because Jaxb is a detached plugin that was installed automatically

Right, but the question is why does this keep on happening, and why doesn't it just get the latest version if that is a dependency? More importantly, why does it not complain if I start fresh with a clean plugin dir and then just install them after? Is it just Jenkins that handles this very poorly, or is this something in the chart?

**Comment by timja** [comment]
I haven't found any official docs on it but it's known as a 'detached plugin'

The list of which is here:
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/split-plugins.txt

There's a bit of info in this Javadoc:
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/plugins/DetachedPluginsUtil.java#L26-L29

basically the plugin is force installed for you if you have any plugin that has an older minimum version than the version it was split out of Jenkins core in.

The version that is installed is a fixed version defined in this excerpt of the `maven-dependency-plugin`:
https://github.com/jenkinsci/jenkins/blob/master/war/pom.xml#L417-L421

These are occasionally updated, normally only if the existing release has a security vulnerability.

----

The simplest fix here is for you add `jaxb` to your plugin list and ensure it uses the latest version, rather than the one that was automatically installed for you

**Comment by panelladavide** [comment]
I had same problem, how to _ensure it uses the latest version_ ?? I have jenkinsci helm chart `3.10.2`. Adding jaxb version to list of plugin do not fix the problem.

**Comment by timja** [comment]
It depends on how you're managing your plugins, but that should solve it unless someone has manually updated it in the UI before or you're using something else for plugins

**Comment by jaw111** [comment]
I've got the same issue here when I delete the pod and it restarts. I've tried with both `jaxb:latest` and `jaxb:jaxb:2.3.6-1` in `controller.installPlugins` list, but no joy either way.

Checked the logs for the `init` container and it _looks_ like it has installed the required version:

```
$ kubectl logs jenkins-0 -n dev -c init | grep jaxb
jaxb 2.3.0.1
Skipping dependency jaxb:2.3.0.1 and its sub-dependencies, because there is a higher version defined on the top level - jaxb:2.3.6-1
jaxb 2.3.0.1
Skipping dependency jaxb:2.3.0.1 and its sub-dependencies, because there is a higher version defined on the top level - jaxb:2.3.6-1
Setting checksum for: jaxb to UaMtJ4PoRLA/2EDw24jj2k07yG4chm3zaNRfCU9KueI=
Setting checksum for: jaxb to UaMtJ4PoRLA/2EDw24jj2k07yG4chm3zaNRfCU9KueI=
jaxb depends on:
Setting checksum for: jaxb to UaMtJ4PoRLA/2EDw24jj2k07yG4chm3zaNRfCU9KueI=
Setting checksum for: jaxb to UaMtJ4PoRLA/2EDw24jj2k07yG4chm3zaNRfCU9KueI=
jaxb 2.3.6-1
Skipping dependency jaxb:2.3.6-1 and its sub-dependencies, because there is a higher version defined on the top level - jaxb:2.3.6-1
Will install new plugin jaxb 2.3.6-1
Will use url: https://updates.jenkins.io/download/plugins/jaxb/2.3.6-1/jaxb.hpi to download jaxb plugin
Downloaded jaxb from https://ftp.halifax.rwth-aachen.de/jenkins/plugins/jaxb/2.3.6-1/jaxb.hpi (attempt 1 of 3)
Downloaded and validated plugin jaxb
Checksum valid for: jaxb
```

Whilst in the logs for `jenkins` container, I still see this:

```
2022-06-24 16:39:20.555+0000 [id=28]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jackson 2 API Plugin v2.13.3-285.vc03c0256d517 (jackson2-api)
java.io.IOException: Failed to load: Jackson 2 API Plugin (jackson2-api 2.13.3-285.vc03c0256d517)
```

I'm using version 4.1.11 of the chart.

**Comment by ujkim** [comment]
Did you solve the problem?
I failed to recover Jenkins due to the same problem.

I want to keep the existing Jenkins pv information.
Is there any way?

**Comment by JihadMotii-REISys** [comment]
@jaw111 I confirm your solution. Removing the old PVC did solve the issue. I'm using ArgoCD to deploy jenkins chart within AWS EKS with EBS for persistence.

**Comment by ujkim** [comment]
@timja Thanks for your advice!!
I added a dependency jaxb latest version, but but it keeps looking for an older version.
Your advice saved my time. Thank you so much.
