### ISSUE TITLE
jenkins execution failed (plugins loading failed)

### ISSUE THREAD

**Issue by ujkim** [jenkinsci/helm-charts#660]
### Describe the bug

https://github.com/jenkinsci/helm-charts/issues/629

Helm chart is not working after one encoding information is corrected and jenkins is restarted.

I've tried the above advice, but it's still failing.

Is there any way to normalize it?

### Version of Helm and Kubernetes

```markdown
- Helm: tested by Lens Helm
- Kubernetes: v.1.22.3
```

### Chart version

jenkins-3.8.6

### What happened?

```bash
1.Jenkins stopped with the issue described above
2.Constantly getting plugin loading errors
3.still happen
...
```

### What you expected to happen?

Jenkins, which was running fine by changing the encoding setting, restarted.

However, since then, the plugin loading fails and does not start.
I want to keep the pv information alive.
`
2022-06-30 13:55:40.924+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2022-06-30 13:55:42.440+0000 [id=20]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 094b3ef5-acce-44a1-b779-0331c059be7a
java.lang.AssertionError: class hudson.security.csrf.DefaultCrumbIssuer is missing its descriptor
	at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1622)
	at hudson.security.csrf.CrumbIssuer.getDescriptor(CrumbIssuer.java:140)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:131)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
......

SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jackson 2 API Plugin v2.13.3-285.vc03c0256d517 (jackson2-api)
java.io.IOException: Failed to load: Jackson 2 API Plugin (2.13.3-285.vc03c0256d517)
 - Update required: JAXB plugin (2.3.0) to be updated to 2.3.6-1 or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-30 13:53:14.962+0000 [id=34]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: REST API Plugin v2.24 (pipeline-rest-api)
java.io.IOException: Failed to load: Pipeline: REST API Plugin (2.24)
 - Failed to load: Jackson 2 API Plugin (2.13.3-285.vc03c0256d517)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)`

### Anything else we need to know?

I am trying this way, is there any way to keep the existing data and save it?

**Comment by JihadMotii-REISys** [comment]
i'm having the same problem with helm chart `4.1.11` as well

**Comment by ujkim** [comment]
@JihadMotii-REISys , I was solved this problem.
After initializing the plugins directory, it worked normally.

https://github.com/jenkinsci/helm-charts/issues/629
