### ISSUE TITLE
Plugin depends on

### ISSUE THREAD

**Issue by pedringcoding** [jenkinsci/helm-charts#704]
### Describe the bug

jenkins-0 pod will not start up. Keep getting back-off error. It's happening all of a sudden. 

### Version of Helm and Kubernetes

```markdown
- Helm: `version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}`
- Kubernetes: `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}`
```

### Chart version

from 4.1.8 to 4.2.2 

### What happened?

```bash
1. helm install would time out, and I keep getting this...
`$ kubectl get pods jenkins-0
NAME        READY   STATUS                  RESTARTS   AGE
jenkins-0   0/2     Init:CrashLoopBackOff   6          1m11s`

2. logs show up for init container:
`Will install new plugin workflow-api 1192.v2d0deb_19d212
io.jenkins.tools.pluginmanager.impl.AggregatePluginPrerequisitesNotMetException: Multiple plugin prerequisites not met:
Plugin workflow-aggregator:581.v0c46fa_697ffd (via pipeline-model-definition:2.2114.v2654ca_721309->git-client:3.12.0) depends on configuration-as-code:1512.vb_79d418d5fc8, but there is an older 
version defined on the top level - configuration-as-code:1429.v09b_044a_c93de,
Plugin git:4.11.3 (via git-client:3.12.0) depends on configuration-as-code:1512.vb_79d418d5fc8, but there is an older version defined on the top level - configuration-as-code:1429.v09b_044a_c93de        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:240)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:189)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:52)
        Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin workflow-aggregator:581.v0c46fa_697ffd (via pipeline-model-definition:2.2114.v2654ca_721309->git-client:3.12.0) depends on configuration-as-code:1512.vb_79d418d5fc8, but there is an older version defined on the top level - configuration-as-code:1429.v09b_044a_c93de
                at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1125)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:692)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
                ... 2 more
        Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin git:4.11.3 (via git-client:3.12.0) depends on configuration-as-code:1512.vb_79d418d5fc8, but there is an 
older version defined on the top level - configuration-as-code:1429.v09b_044a_c93de
                at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1125)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:692)
                at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
                ... 2 more
Multiple plugin prerequisites not met:
Plugin workflow-aggregator:581.v0c46fa_697ffd (via pipeline-model-definition:2.2114.v2654ca_721309->git-client:3.12.0) depends on configuration-as-code:1512.vb_79d418d5fc8, but there is an older 
version defined on the top level - configuration-as-code:1429.v09b_044a_c93de,
Plugin git:4.11.3 (via git-client:3.12.0) depends on configuration-as-code:1512.vb_79d418d5fc8, but there is an older version defined on the top level - configuration-as-code:1429.v09b_044a_c93de`
```

### What you expected to happen?

Could I update for the conflicting plugin version without having to create a custom image?

### Anything else we need to know?

I dont apply values.yaml in this tests

**Comment by timja** [comment]
the plugins need bumping in this helm chart (side note we really need to automate this 😢 )

**Comment by pedringcoding** [comment]
Fixed it by adding the following setting in the values file.
```
controller:
    install plugins:
      - configuration-as-code:1512.vb_79d418d5fc8
```

But must it be the correct solution?
If you allow me to do so, I can send a _pull request_ with a _hotfix branch_ for the change over the default `values.yaml` file.

**Comment by timja** [comment]
Anyone can send a pull request, you just need to [fork the repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and send it from your fork, that would be appreciated
