### ISSUE TITLE
Unable to install Jenkins if k8s >= v1.25.0

### ISSUE THREAD

**Issue by ShihouinYoruichi** [jenkinsci/helm-charts#717]
### Describe the bug

When installing Jenkins with Helm, if Kubernetes version >= v1.25.0, the following DNS resolving issue happens.
It does not happen until Kubernetes version v1.24.6
I tried the recently released v1.25.2, but it still did not fix this issue.
I even checked [this workaround](https://github.com/jenkinsci/helm-charts/issues/511), but unfortunately it did not help neither.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.9.4
- Kubernetes: v1.25.2
```

### Chart version

jenkins-4.2.6

### What happened?

```bash
1. You should just install Jenkins Helm chart normally
```

### What you expected to happen?

kubectl logs jenkins-0 -c init
=================

disable Setup Wizard
download plugins
File containing list of plugins to be downloaded: /var/jenkins_home/plugins.txt
Reading in plugins from /var/jenkins_home/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
Will use war file: /usr/share/jenkins/jenkins.war

Retrieving update center information
Update center URL: https://updates.jenkins.io/update-center.json?version=2.371
Cache miss for: update-center-2.371

... (the init container was stuck here and created no more logs)

### How to reproduce it

```markdown
helm install jenkins jenkins/jenkins
```

**Comment by timja** [comment]
Unsure I don't have a cluster of that version to test with currently.

**Comment by ShihouinYoruichi** [comment]
> Unsure I don't have a cluster of that version to test with currently.

I got it. As for me, I was testing them with Minikube on the local.

**Comment by lknite** [comment]
With 1.25.3 I get past the init but jenkins doesn't come up, keep seeing errors like:
```
[jenkins-0 jenkins] 2023-01-19 17:38:52.297+0000 [id=11]        WARNING h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 9af9934d-a4d9-4fe3-b370-6aa0fd334c6b
[jenkins-0 jenkins] java.lang.AssertionError: class hudson.security.csrf.DefaultCrumbIssuer is missing its descriptor
[jenkins-0 jenkins]     at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1634)
[jenkins-0 jenkins]     at hudson.security.csrf.CrumbIssuer.getDescriptor(CrumbIssuer.java:141)
[jenkins-0 jenkins]     at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:132)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
[jenkins-0 jenkins]     at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:170)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
[jenkins-0 jenkins]     at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
[jenkins-0 jenkins]     at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
[jenkins-0 jenkins]     at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
[jenkins-0 jenkins]     at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
[jenkins-0 jenkins]     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:549)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1383)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
[jenkins-0 jenkins]     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1305)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.Server.handle(Server.java:563)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
[jenkins-0 jenkins]     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
[jenkins-0 jenkins]     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
[jenkins-0 jenkins]     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
[jenkins-0 jenkins]     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
[jenkins-0 jenkins]     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
[jenkins-0 jenkins]     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
[jenkins-0 jenkins]     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
[jenkins-0 jenkins]     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:199)
[jenkins-0 jenkins]     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
[jenkins-0 jenkins]     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
[jenkins-0 jenkins]     at java.base/java.lang.Thread.run(Thread.java:829)
[jenkins-0 jenkins] 2023-01-19 17:39:01.685+0000 [id=30]        INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
[jenkins-0 jenkins] 2023-01-19 17:39:01.784+0000 [id=30]        INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
[jenkins-0 jenkins] 2023-01-19 17:39:01.981+0000 [id=29]        INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
[jenkins-0 jenkins] 2023-01-19 17:39:05.287+0000 [id=29]        INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
[jenkins-0 jenkins] 2023-01-19 17:39:05.288+0000 [id=29]        INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
[jenkins-0 jenkins] WARNING: An illegal reflective access operation has occurred
[jenkins-0 jenkins] WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/var/jenkins_cache/war/WEB-INF/lib/groovy-all-2.4.21.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
[jenkins-0 jenkins] WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
[jenkins-0 jenkins] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[jenkins-0 jenkins] WARNING: All illegal access operations will be denied in a future release
[jenkins-0 jenkins] 2023-01-19 17:39:07.382+0000 [id=30]        INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
[jenkins-0 jenkins] 2023-01-19 17:39:07.481+0000 [id=29]        INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
[jenkins-0 jenkins] 2023-01-19 17:39:08.786+0000 [id=30]        INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
[jenkins-0 jenkins] 2023-01-19 17:39:09.491+0000 [id=22]        INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
[jenkins-0 config-reload] [2023-01-19 17:39:11] POST request sent to http://localhost:8081/reload-configuration-as-code/?casc-reload-token=jenkins-0. Response: 403 Forbidden <html>
[jenkins-0 config-reload] <head>
[jenkins-0 config-reload] <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
[jenkins-0 config-reload] <title>Error 403 No valid crumb was included in the request</title>
[jenkins-0 config-reload] </head>
[jenkins-0 config-reload] <body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>
[jenkins-0 config-reload] <table>
[jenkins-0 config-reload] <tr><th>URI:</th><td>/reload-configuration-as-code/</td></tr>
[jenkins-0 config-reload] <tr><th>STATUS:</th><td>403</td></tr>
[jenkins-0 config-reload] <tr><th>MESSAGE:</th><td>No valid crumb was included in the request</td></tr>
[jenkins-0 config-reload] <tr><th>SERVLET:</th><td>Stapler</td></tr>
[jenkins-0 config-reload] </table>
[jenkins-0 config-reload] <hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 10.0.12</a><hr/>
[jenkins-0 config-reload] 
[jenkins-0 config-reload] </body>
[jenkins-0 config-reload] </html>
```

**Comment by lknite** [comment]
@ShihouinYoruichi are you still experiencing this issue?  I'm not seeing this on v1.25.3

**Comment by ShihouinYoruichi** [comment]
@lknite 
Thank you for sharing your experience. I just tried again with the same condition as you and confirmed that the problem remained.

I'm not sure why there is still no progress on this issue, as the latest of k8s version is already 1.26.x and EOP for 1.25.x is already coming.

**Comment by ShihouinYoruichi** [comment]
@lknite 
Thank you for sharing your experience. I just tried again with the same condition as yours and confirmed that the problem remained.

I'm not sure why there is still no progress on this issue, as the latest of k8s version is already 1.26.x and EOP for 1.25.x is already coming.

**Comment by lemeurherve** [comment]
@ShihouinYoruichi do you still have the problem? We've deployed this chart in Jenkins Infrastructure without any issue on kubernetes 1.25 and 1.26.
