### ISSUE TITLE
java.io.IOException: Failed to load: Kubernetes plugin (kubernetes 3923.v294a_d4250b_91)

### ISSUE THREAD

**Issue by binarywang** [jenkinsci/helm-charts#871]
### Describe the bug

After upgrade to version 4.3.24, my jenkins pods can not start any more, it produces error logs like this: 
```
Running from: /usr/share/jenkins/jenkins.war
Tue, Jun 6 2023 5:40:58 pm | 2023-06-06 09:40:58.485+0000 [id=1] INFO winstone.Logger#logInternal: Beginning extraction from war file
Tue, Jun 6 2023 5:40:58 pm | 2023-06-06 09:40:58.698+0000 [id=1] WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
Tue, Jun 6 2023 5:40:58 pm | 2023-06-06 09:40:58.875+0000 [id=1] INFO org.eclipse.jetty.server.Server#doStart: jetty-10.0.13; built: 2022-12-07T20:13:20.134Z; git: 1c2636ea05c0ca8de1ffd6ca7f3a98ac084c766d; jvm 11.0.19+7
Tue, Jun 6 2023 5:40:59 pm | 2023-06-06 09:40:59.795+0000 [id=1] INFO o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
Tue, Jun 6 2023 5:40:59 pm | 2023-06-06 09:40:59.931+0000 [id=1] INFO o.e.j.s.s.DefaultSessionIdManager#doStart: Session workerName=node0
Tue, Jun 6 2023 5:41:01 pm | 2023-06-06 09:41:01.154+0000 [id=1] INFO hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Tue, Jun 6 2023 5:41:01 pm | 2023-06-06 09:41:01.652+0000 [id=1] INFO o.e.j.s.handler.ContextHandler#doStart: Started w.@61e45f87{Jenkins v2.401.1,/,file:///var/jenkins_cache/war/,AVAILABLE}{/var/jenkins_cache/war}
Tue, Jun 6 2023 5:41:01 pm | 2023-06-06 09:41:01.684+0000 [id=1] INFO o.e.j.server.AbstractConnector#doStart: Started ServerConnector@192c3f1e{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
Tue, Jun 6 2023 5:41:01 pm | 2023-06-06 09:41:01.711+0000 [id=1] INFO org.eclipse.jetty.server.Server#doStart: Started Server@157853da{STARTING}[10.0.13,sto=0] @4658ms
Tue, Jun 6 2023 5:41:01 pm | 2023-06-06 09:41:01.763+0000 [id=23] INFO winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
Tue, Jun 6 2023 5:41:02 pm | 2023-06-06 09:41:02.365+0000 [id=29] INFO jenkins.InitReactorRunner$1#onAttained: Started initialization
Tue, Jun 6 2023 5:41:03 pm | 2023-06-06 09:41:03.409+0000 [id=29] INFO jenkins.InitReactorRunner$1#onAttained: Listed all plugins
Tue, Jun 6 2023 5:41:04 pm | 2023-06-06 09:41:04.298+0000 [id=31] SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Metrics Plugin v4.2.18-438.v0ede325a_4c68 (metrics)
Tue, Jun 6 2023 5:41:04 pm | java.io.IOException: Failed to load: Metrics Plugin (metrics 4.2.18-438.v0ede325a_4c68)
Tue, Jun 6 2023 5:41:04 pm | - Update required: Jackson 2 API Plugin (jackson2-api 2.15.0-334.v317a_165f9b_7c) to be updated to 2.15.1-344.v6eb_55303dc3e or higher
Tue, Jun 6 2023 5:41:04 pm | at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:994)
Tue, Jun 6 2023 5:41:04 pm | at hudson.PluginManager$2$1$1.run(PluginManager.java:555)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:177)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
Tue, Jun 6 2023 5:41:04 pm | at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
Tue, Jun 6 2023 5:41:04 pm | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
Tue, Jun 6 2023 5:41:04 pm | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Tue, Jun 6 2023 5:41:04 pm | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Tue, Jun 6 2023 5:41:04 pm | at java.base/java.lang.Thread.run(Thread.java:829)
Tue, Jun 6 2023 5:41:04 pm | 2023-06-06 09:41:04.303+0000 [id=29] SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Kubernetes plugin v3923.v294a_d4250b_91 (kubernetes)
Tue, Jun 6 2023 5:41:04 pm | java.io.IOException: Failed to load: Kubernetes plugin (kubernetes 3923.v294a_d4250b_91)
Tue, Jun 6 2023 5:41:04 pm | - Failed to load: Metrics Plugin (metrics 4.2.18-438.v0ede325a_4c68)
Tue, Jun 6 2023 5:41:04 pm | at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:994)
Tue, Jun 6 2023 5:41:04 pm | at hudson.PluginManager$2$1$1.run(PluginManager.java:555)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:177)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
Tue, Jun 6 2023 5:41:04 pm | at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
Tue, Jun 6 2023 5:41:04 pm | at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
Tue, Jun 6 2023 5:41:04 pm | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
Tue, Jun 6 2023 5:41:04 pm | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Tue, Jun 6 2023 5:41:04 pm | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Tue, Jun 6 2023 5:41:04 pm | at java.base/java.lang.Thread.run(Thread.java:829)
Tue, Jun 6 2023 5:41:13 pm | 2023-06-06 09:41:13.510+0000 [id=31] INFO jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
Tue, Jun 6 2023 5:41:13 pm | 2023-06-06 09:41:13.658+0000 [id=30] INFO jenkins.InitReactorRunner$1#onAttained: Started all plugins
Tue, Jun 6 2023 5:41:14 pm | WARNING: An illegal reflective access operation has occurred
Tue, Jun 6 2023 5:41:14 pm | WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/var/jenkins_cache/war/WEB-INF/lib/groovy-all-2.4.21.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
Tue, Jun 6 2023 5:41:14 pm | WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
Tue, Jun 6 2023 5:41:14 pm | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Tue, Jun 6 2023 5:41:14 pm | WARNING: All illegal access operations will be denied in a future release
Tue, Jun 6 2023 5:41:16 pm | 2023-06-06 09:41:16.400+0000 [id=31] INFO jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
Tue, Jun 6 2023 5:41:16 pm | 2023-06-06 09:41:16.521+0000 [id=30] WARNING o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class com.gitee.jenkins.gitee.api.impl.GiteeV5ClientBuilder$1 in file:/var/jenkins_home/plugins/gitee/WEB-INF/lib/gitee-1.2.7.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
Tue, Jun 6 2023 5:41:17 pm | 2023-06-06 09:41:17.759+0000 [id=30] INFO jenkins.InitReactorRunner$1#onAttained: System config loaded
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.616+0000 [id=30] SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
Tue, Jun 6 2023 5:41:18 pm | java.lang.IllegalArgumentException: No hudson.slaves.Cloud implementation found for kubernetes
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$lookupDescriptor$11(HeteroDescribableConfigurator.java:211)
Tue, Jun 6 2023 5:41:18 pm | at io.vavr.control.Option.orElse(Option.java:321)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lookupDescriptor(HeteroDescribableConfigurator.java:210)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:84)
Tue, Jun 6 2023 5:41:18 pm | at io.vavr.Tuple2.apply(Tuple2.java:238)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:343)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:776)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:712)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:776)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:761)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:637)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:306)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:298)
Tue, Jun 6 2023 5:41:18 pm | Caused: java.lang.reflect.InvocationTargetException
Tue, Jun 6 2023 5:41:18 pm | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Tue, Jun 6 2023 5:41:18 pm | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Tue, Jun 6 2023 5:41:18 pm | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Tue, Jun 6 2023 5:41:18 pm | at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
Tue, Jun 6 2023 5:41:18 pm | Caused: java.lang.Error
Tue, Jun 6 2023 5:41:18 pm | at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:115)
Tue, Jun 6 2023 5:41:18 pm | at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
Tue, Jun 6 2023 5:41:18 pm | at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
Tue, Jun 6 2023 5:41:18 pm | at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
Tue, Jun 6 2023 5:41:18 pm | at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.lang.Thread.run(Thread.java:829)
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.620+0000 [id=22] SEVERE hudson.util.BootFailure#publish: Failed to initialize Jenkins
Tue, Jun 6 2023 5:41:18 pm | java.lang.IllegalArgumentException: No hudson.slaves.Cloud implementation found for kubernetes
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$lookupDescriptor$11(HeteroDescribableConfigurator.java:211)
Tue, Jun 6 2023 5:41:18 pm | at io.vavr.control.Option.orElse(Option.java:321)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lookupDescriptor(HeteroDescribableConfigurator.java:210)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:84)
Tue, Jun 6 2023 5:41:18 pm | at io.vavr.Tuple2.apply(Tuple2.java:238)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:343)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:776)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:712)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:776)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:761)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:637)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:306)
Tue, Jun 6 2023 5:41:18 pm | at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:298)
Tue, Jun 6 2023 5:41:18 pm | Caused: java.lang.reflect.InvocationTargetException
Tue, Jun 6 2023 5:41:18 pm | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Tue, Jun 6 2023 5:41:18 pm | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Tue, Jun 6 2023 5:41:18 pm | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Tue, Jun 6 2023 5:41:18 pm | at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
Tue, Jun 6 2023 5:41:18 pm | Caused: java.lang.Error
Tue, Jun 6 2023 5:41:18 pm | at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:115)
Tue, Jun 6 2023 5:41:18 pm | at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
Tue, Jun 6 2023 5:41:18 pm | at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
Tue, Jun 6 2023 5:41:18 pm | at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
Tue, Jun 6 2023 5:41:18 pm | at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.lang.Thread.run(Thread.java:829)
Tue, Jun 6 2023 5:41:18 pm | Caused: org.jvnet.hudson.reactor.ReactorException
Tue, Jun 6 2023 5:41:18 pm | at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:290)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.model.Jenkins.executeReactor(Jenkins.java:1199)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.model.Jenkins.<init>(Jenkins.java:987)
Tue, Jun 6 2023 5:41:18 pm | at hudson.model.Hudson.<init>(Hudson.java:86)
Tue, Jun 6 2023 5:41:18 pm | at hudson.model.Hudson.<init>(Hudson.java:82)
Tue, Jun 6 2023 5:41:18 pm | at hudson.WebAppMain$3.run(WebAppMain.java:247)
Tue, Jun 6 2023 5:41:18 pm | Caused: hudson.util.HudsonFailedToLoad
Tue, Jun 6 2023 5:41:18 pm | at hudson.WebAppMain$3.run(WebAppMain.java:264)
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.647+0000 [id=22] INFO hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.690+0000 [id=22] INFO jenkins.model.Jenkins$16#onAttained: Started termination
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.755+0000 [id=22] INFO jenkins.model.Jenkins$16#onAttained: Completed termination
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.755+0000 [id=22] INFO jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.762+0000 [id=22] INFO jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.883+0000 [id=22] INFO jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.935+0000 [id=22] INFO jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.937+0000 [id=22] SEVERE jenkins.model.Jenkins#_cleanUpPluginServletFilters: Failed to stop filters
Tue, Jun 6 2023 5:41:18 pm | java.lang.ClassNotFoundException: org.jenkinsci.plugins.ssegateway.SubscriptionConfigQueue$SubscriptionConfig
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:35)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
Tue, Jun 6 2023 5:41:18 pm | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Tue, Jun 6 2023 5:41:18 pm | Caused: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/ssegateway/SubscriptionConfigQueue$SubscriptionConfig
Tue, Jun 6 2023 5:41:18 pm | at org.jenkinsci.plugins.ssegateway.SubscriptionConfigQueue.stop(SubscriptionConfigQueue.java:106)
Tue, Jun 6 2023 5:41:18 pm | at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.destroy(Endpoint.java:253)
Tue, Jun 6 2023 5:41:18 pm | at hudson.util.PluginServletFilter.cleanUp(PluginServletFilter.java:185)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.model.Jenkins._cleanUpPluginServletFilters(Jenkins.java:3927)
Tue, Jun 6 2023 5:41:18 pm | at jenkins.model.Jenkins.cleanUp(Jenkins.java:3624)
Tue, Jun 6 2023 5:41:18 pm | at hudson.WebAppMain$3.run(WebAppMain.java:268)
Tue, Jun 6 2023 5:41:18 pm | 2023-06-06 09:41:18.938+0000 [id=22] INFO hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
```

### Version of Helm and Kubernetes

```markdown
- Helm: 
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
- Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T16:52:07Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T16:52:07Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Chart version

4.3.24

### What happened?

```bash
1. upgrade jenkin helm
helm upgrade jenkins ...
```

### What you expected to happen?

jenkins start properly

### How to reproduce it

```markdown
helm upgrade jenkins https://github.com/jenkinsci/helm-charts/releases/download/jenkins-4.3.24/jenkins-4.3.24.tgz -n jenkins
```

**Comment by kvanzuijlen** [comment]
@binarywang Are you still running into this with the latest version?

**Comment by timja** [comment]
This will have been fixed at some point
