### ISSUE TITLE
helm install faild

### ISSUE THREAD

**Issue by zouchengli** [jenkinsci/helm-charts#938]
### Describe the bug

disable Setup Wizard
download plugins
File containing list of plugins to be downloaded: /var/jenkins_home/plugins.txt
Reading in plugins from /var/jenkins_home/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
Will use war file: /usr/share/jenkins/jenkins.war

Retrieving update center information
Update center URL: https://updates.jenkins.io/update-center.json?version=2.414.3
Cache miss for: update-center-2.414.3
Unable to retrieve JSON from https://updates.jenkins.io/update-center.json?version=2.414.3: Certificate for <updates.jenkins.io> doesn't match any of the subject alternative names: [*.mycompanyname.com]
Unable to retrieve JSON from https://updates.jenkins.io/update-center.json?version=2.414.3: Certificate for <updates.jenkins.io> doesn't match any of the subject alternative names: [*.mycompanyname.com]
io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:839)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:860)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:225)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:189)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:52)
Caused by: java.io.IOException: Unable to retrieve JSON from https://updates.jenkins.io/update-center.json?version=2.414.3: Certificate for <updates.jenkins.io> doesn't match any of the subject alternative names: [*.mycompanyname.com]
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getViaHttpWithResponseHandler(PluginManager.java:1374)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:825)
        ... 4 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <updates.jenkins.io> doesn't match any of the subject alternative names: [*.mycompanyname.com]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:507)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getViaHttpWithResponseHandler(PluginManager.java:1366)
        ... 5 more
Error getting update center json

### Version of Helm and Kubernetes

```markdown
- Helm: version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.21.3"}
- Kubernetes: 
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.0
```

### Chart version

4.8.2

**Comment by zouchengli** [comment]
The reason is my dns resolution problem, because my k8s working node sets the company's search domain name, so when requesting dns resolution in the pod, some external domain names, such as the uc domain name of jenkins, will be spliced into updates.jenkins later. .io.mycompanyname.com
